### ISSUE TITLE
I think I found a bug when using mod_wsgi together with django when using --url-alias directive

### ISSUE THREAD

**Issue by linxi-1214** [GrahamDumpleton/mod_wsgi#183] opened 2017-01-10 03:47 UTC
my command line:
python manage.py runmodwsgi \                                              
     --host=0.0.0.0 \                                                             
     --port=${port} \                                                             
     --document-root=${currpath} \                                                
     --server-root=${HOME}/etc/httpd \                                            
     --reload-on-changes \                                                        
     --access-log --startup-log \                                                 
     --url-alias /static ${HOME}/download  \                                                                                                             
     --log-level=debug & 

I got an error:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/mod_wsgi/server/management/commands/runmodwsgi.py", line 108, in handle
    'start-server', args, options)
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/mod_wsgi/server/__init__.py", line 3300, in _cmd_setup_server
    generate_apache_config(options)
  File "/home/wangxb/pyenv3.6/lib/python3.6/site-packages/mod_wsgi/server/__init__.py", line 1006, in generate_apache_config
    for mount_point, target in sorted(options['url_aliases'], reverse=True):
TypeError: '<' not supported between instances of 'tuple' and 'list'

I look up the source code, and I found this is because line 97 in runmodwsgi.py,  insert an tuple element into url_aliases variable based on my django settings. And  generate another element from my command line , the element type is list, finally the variable's value is : [('/static', 'static'), ['/static', '/home/wangxb/download']]. Then sorted([('/static', 'static'), ['/static', '/home/wangxb/download']]) raise the error in mod_wsgi/server/__init__.py line 1006.

**Comment by GrahamDumpleton** [comment] 2017-01-11 00:43
What version of Django are you using?

This may be caused by something the Django 1.10 argument parser is doing, or some compatibility conversions done to allow code to work with both Django <1.10 and >=1.10. The standard options list module would generate a list of tuples. I will have to dig into it, but need to know the Django version.

BTW, why are you setting ``--url-alias /static`` anyway. The ``runmodwsgi`` command will set the ``/static`` URL for you based on what ``STATIC_ROOT`` is set to in your Django settings file. I don't think you should be trying to override it to a different directory, else it will not correctly pick up the files from where ``collectstatic`` put them.

**Comment by GrahamDumpleton** [comment] 2017-01-11 00:45
I can't replicate this with Django 1.10. As well as what Django version are you using, what mod_wsgi version are you using?

**Comment by GrahamDumpleton** [comment] 2017-01-11 00:48
Specific to Django 1.0 on Python 3.6 (or maybe 3.X).

**Comment by linxi-1214** [comment] 2017-01-11 01:38
my enviroment is :
    mod-wsgi (4.5.13)
    Django (1.10.2)
    Python 3.6
I tried on Python3.4 and Python 3.6, didn't try on Python 2.7

**Comment by GrahamDumpleton** [comment] 2017-01-21 03:37
Sorry for the delay on this, been on a trip and quite busy. Also wasn't sure of the best way to detect this. Ended up with a hack that introspected the type of existing items in the list and used the same type. Is fixed on develop branch. You can try:

* https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip

**Comment by GrahamDumpleton** [comment] 2017-06-04 01:16
This should have been released back in 4.5.14. Closing issue.

**Closed by GrahamDumpleton** 2017-06-04 01:16 UTC
