### ISSUE TITLE
mod_wsgi giving error with python3.6 + Django 2.2.7 + apache2.4

### ISSUE THREAD

**Issue by sanjaytech9** [GrahamDumpleton/mod_wsgi#498] opened 2019-12-03 09:28 UTC
I am facing issue while running project on wsgi as following.
`
Traceback (most recent call last):
	File "/var/www/project_folder/project/wsgi.py", line 11, in <module>
from django.core.wsgi import get_wsgi_application
 ImportError: No module named 'django'
 Target WSGI script '/var/www/project_folder/project/wsgi.py' cannot be loaded as Python module.
 mod_wsgi (pid=29917): Exception occurred processing WSGI script '/var/www/project_folder/project/wsgi.py'.
 Traceback (most recent call last):
   File "/var/www/project_folder/project/wsgi.py", line 11, in <module>
     from django.core.wsgi import get_wsgi_application
 ImportError: No module named 'django'
`

**Comment by GrahamDumpleton** [comment] 2019-12-03 09:51
You would need to provide what configuration you are using and where Django is installed.

The error usually indicates you have Django installed into a Python virtual environment or in a per user site-packages directory, but mod_wsgi is only using the system packages.

You need to tell mod_wsgi where the Python virtual environment is if one is being used.

If you installed packages into a per user site-packages directory using `pip install --user`, you need to use a Python virtual environment instead. Because Apache runs as its own user, it will not look in the per user site-packages directory of your user.

**Comment by sanjaytech9** [comment] 2019-12-03 10:23
Thanks, Basically I installed this WSGI inside the environment using pip3 for python3.6 version... and it return the version like 

(venv) root@sIP:/etc/apache2/sites-available# mod_wsgi-express module-config
LoadModule wsgi_module "/var/www/project/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"



But while I run site I see the error.log with 
[Tue Dec 03 03:06:51.130316 2019] [mpm_event:notice] [pid 29914:tid 140223177922432] AH00491: caught SIGTERM, shutting down
[Tue Dec 03 03:06:52.175664 2019] [wsgi:warn] [pid 31673:tid 140442623440768] mod_wsgi: Compiled for Python/3.5.1+.
[Tue Dec 03 03:06:52.175704 2019] [wsgi:warn] [pid 31673:tid 140442623440768] mod_wsgi: Runtime using Python/3.5.2.
[Tue Dec 03 03:06:52.176366 2019] [mpm_event:notice] [pid 31673:tid 140442623440768] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Tue Dec 03 03:06:52.176381 2019] [core:notice] [pid 31673:tid 140442623440768] AH00094: Command line: '/usr/sbin/apache2'

I am curious why it is compiling for python3.5.1 instead of 3.6

**Comment by GrahamDumpleton** [comment] 2019-12-03 11:02
The `module-config` command should also in that case have output:

```
WSGIPythonHome /var/www/project
```

Did you forget to include that? Do you have that `WSGIPythonHome` directive line in your Apache config?

The value to `WSGIPythoHome` should be the value of `sys.prefix` as shown by Python interpreter.

**Comment by GrahamDumpleton** [comment] 2020-02-17 00:00
No further followup so assumed got it working or gave up. Closing issue.

**Closed by GrahamDumpleton** 2020-02-17 00:00 UTC

**Comment by ajsicek** [comment] 2020-03-04 16:09
Having same issue. Running debian apache, and mod wsgi and django (installed via pip3 install --user django ) 
After spending hours to find a solution I finally stumbled on your post.
@GrahamDumpleton Do I get it right, that I can not make it work in this setup?
If yes It would be great to have that written somewhere maybe in Django deployment with mod_wsgi documentation. So people do know from the very start.
What is the proposed solution? different way of deploying (which)? different way of installing django?  If I get it right sudo pip install django will not help either right? apt-get install django is only version 2.2

**Comment by GrahamDumpleton** [comment] 2020-03-04 19:36
@ajsicek If you are talking about using a per user site packages, there are multiple solutions. Please though go create a separate issue which details the specifics of your issue (including config, errors etc) so it can be confirmed what you problem is. Don't use an existing issue, because it can't be guaranteed that your issue is the same and having a discussion on an existing issue for another user makes things really confusing.
