### ISSUE TITLE
Keystone thread crash with coredump during apache re-starting

### ISSUE THREAD

**Issue by SlavaValAl** [GrahamDumpleton/mod_wsgi#132] opened 2016-05-05 22:38 UTC
Apache produces a lot of coredumps during apache start/stop. 

I have pasted gdb backtrace on pastebin - http://pastebin.com/5DLMbiM8
mod_wsgi version is libapache2-mod-wsgi_3.4

**Comment by GrahamDumpleton** [comment] 2018-01-22 13:06
Closing this as effectively a duplicate of #81.

**Closed by GrahamDumpleton** 2018-01-22 13:06 UTC
