### ISSUE TITLE
mod_wsgi does not load django project with Stanford Stanza module

### ISSUE THREAD

**Issue by adam-shaker** [GrahamDumpleton/mod_wsgi#583] opened 2020-06-11 11:56 UTC
Hello,

I have a django project with Stanford's Stanza Library included in the project. 
If I execute the django app using runserver, everything runs fine and I can use the application.

Django: 3.0.7
Stanza: 1.0.1 (https://stanfordnlp.github.io/stanza/index.html)
mod_wsgi: 4.7.1
Centos: 8.1.1911 (Core)
Apache: 2.4.37
Python: 3.8.3 (in a virtual environment)
Conda: 4.8.2

When I load the application using mod_wsgi in apache using the following apache configuration, I keep getting 500 Internal Server Error.

```
LoadModule wsgi_module "/usr/lib64/httpd/modules/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"
WSGIPythonHome "/opt/anaconda3/envs/tempenv"

<VirtualHost *:80>
        WSGIDaemonProcess myapp processes=4  threads=16  python-path=/opt/projects/new_project:/opt/anaconda3/envs/tempenv/lib/python3.8/site-packages
        WSGIProcessGroup myapp
        WSGIScriptAlias / /opt/projects/new_project/new_project/wsgi.py
        Alias /static /opt/projects/new_project/static
        <Directory /opt/projects/new_project/static>
         Require all granted
        </Directory>

        <Directory /opt/projects/new_project/new_project>
           <Files wsgi.py>
               Require all granted
           </Files>
        </Directory>
        WSGIApplicationGroup %{GLOBAL}
</VirtualHost>
```

Apache Error Log prints the following error:

```
[Thu Jun 11 11:16:01.197323 2020] [wsgi:info] [pid 24215:tid 140588572370688] [] mod_wsgi (pid=24215, process='myapp', application=''): Loading Python script file '/opt/projects/new_project/new_project/wsgi.py'.
terminate called after throwing an instance of 'Xbyak::Error'
  what():  can't protect
[Thu Jun 11 11:16:02.290740 2020] [wsgi:error] [pid 24216:tid 140588253447936] [] Truncated or oversized response headers received from daemon process 'myapp': /opt/projects/new_project/new_project/wsgi.py
[Thu Jun 11 11:16:02.460253 2020] [core:notice] [pid 24209:tid 140588903364864] AH00052: child pid 24215 exit signal Aborted (6)
```

I read the C Extension Modules do not work in the sub-interpreter and have to be forced to work in the main interpreter. Tried adding `WSGIApplicationGroup %{GLOBAL}` but that also didn't work.
I have tried various configurations and none of them have seemed to work. Any suggestions would be welcome.

Here are all the modules in the current virtual environment for reference:
```
asgiref==3.2.7
certifi==2020.4.5.1
chardet==3.0.4
Django==3.0.7
djangorestframework==3.11.0
future==0.18.2
idna==2.9
mod-wsgi==4.7.1
protobuf==3.12.2
pytz==2020.1
requests==2.23.0
six==1.15.0
sqlparse==0.3.1
stanza==1.0.1
torch==1.5.0
tqdm==4.46.1
urllib3==1.25.9
```

**Comment by GrahamDumpleton** [comment] 2020-06-11 12:16
Do you have mod_ssl enabled in Apache.

Anaconda Python cannot be used if you have mod_ssl enabled because Anaconda Python doesn't use the system SSL and crypto libraries and ships its own. Thus any attempt to use SSL or crypto in Python can cause crashes or unexpected failures.

That is worst case problem, but your issue may be more simple than that. It could be a permissions issue since your code will run as the Apache user and not you. It also could be due to trying to use relative paths to open files, since Apache process will run with a working directory of ``/`` and not where your code is located.

For some of these sorts of issues read through:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html

It would help though if you can work out what C/C++ library is generating the following error and under what conditions it would do so:

```
terminate called after throwing an instance of 'Xbyak::Error'
  what():  can't protect
```

That is aborts the whole process is rather brutal, rather than the error being raised up through the Python extension wrapper.

**Comment by adam-shaker** [comment] 2020-06-11 17:09
mod_ssl doesn't seem to be the problem. The way I isolated the problem to be related to stanza is, I installed the given requirements.txt in a fresh python 3.8 virtual environment, started a blank django project and provided the given apache configuration.
The project executed fine with the django welcome screen loading correctly. 
I just made 1 single import in views.py `import stanza` and reloaded/restarted httpd and immediately it failed with the error above.
To be honest I have zero experience in debugging C/C++ libraries, can you provide some light into what might be the issue or how I can figure it out?

**Comment by GrahamDumpleton** [comment] 2020-06-12 00:10
I already suggested two common possibilities for the cause and gave you a link to documentation which explained those and more. Have you read that document and verify that it cannot be those. Repeating them, and adding one more:

* The code when run under mod_wsgi run as the Apache user. That user may not have access to the directories/files it is trying to read or write.
* The code may be trying to accessing directories/files by a relative path because you didn't give a full path name. Under Apache though the current working directory isn't where your code is like when you run the command line.
* Are you setting environment variables in your user account in order for it to work from the command line. Environment variables set in your user account will not be used by the Apache user. Environment variables need to be set in the WSGI script file before importing any modules which may need them.

Also google for that error message. There are other people out there who have seen the same error, so read those discussions to see if the solutions apply to your case.

**Comment by GrahamDumpleton** [comment] 2021-08-02 01:55
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.

**Closed by GrahamDumpleton** 2021-08-02 01:55 UTC
