### ISSUE TITLE
mod_wsgi is failing to compile on Feb 10/2020 when a new virtualenv version is released

### ISSUE THREAD

**Issue by sinerzxa** [GrahamDumpleton/mod_wsgi#519] opened 2020-02-10 21:56 UTC
Hi There,

I failed to compile mod_wsgi today, the only change is new release 20.0.1 virtualenv is released today and the compile will succeed if using last version. Is it a convention to freeze virtualenv version some way? Any suggestion is appreciated. Thanks!

The failure message is:
   Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Apache24\htdocs\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\7zS8E39DA62\\cloud-eweb-api\\cloud_eweb_cmd\\logs\\pip-install-ggiqav2y\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\7zS8E39DA62\\cloud-eweb-api\\cloud_eweb_cmd\\logs\\pip-install-ggiqav2y\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Administrator\AppData\Local\Temp\7zS8E39DA62\cloud-eweb-api\cloud_eweb_cmd\logs\pip-wheel-cu2thp_t'
       cwd: C:\Users\Administrator\AppData\Local\Temp\7zS8E39DA62\cloud-eweb-api\cloud_eweb_cmd\logs\pip-install-ggiqav2y\mod-wsgi\
  Complete output (105 lines):
  c:\python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\mod_wsgi
  copying src\__init__.py -> build\lib.win32-3.6\mod_wsgi
  creating build\lib.win32-3.6\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win32-3.6\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win32-3.6\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win32-3.6\mod_wsgi\server
  creating build\lib.win32-3.6\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win32-3.6\mod_wsgi\server\management
  creating build\lib.win32-3.6\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.6\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win32-3.6\mod_wsgi\server\management\commands
  creating build\lib.win32-3.6\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win32-3.6\mod_wsgi\docs
  creating build\lib.win32-3.6\mod_wsgi\images
  copying images\__init__.py -> build\lib.win32-3.6\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win32-3.6\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win32-3.6
  creating build\temp.win32-3.6\Release
  creating build\temp.win32-3.6\Release\src
  creating build\temp.win32-3.6\Release\src\server
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.6\Release\src/server\mod_wsgi.obj
  mod_wsgi.c
  c:\python36\include\pyconfig.h(321): warning C4005: 'PLATFORM': macro redefinition
  c:\apache24\include\os.h(44): note: see previous definition of 'PLATFORM'
  src/server\mod_wsgi.c(1331): warning C4244: 'function': conversion from '__int64' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1343): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1349): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1366): warning C4244: 'function': conversion from 'apr_off_t' to 'std::apr_size_t', possible loss of data
  src/server\mod_wsgi.c(1390): warning C4244: 'function': conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1431): warning C4244: 'function': conversion from '__int64' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1447): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1457): warning C4244: 'function': conversion from 'apr_off_t' to 'std::apr_size_t', possible loss of data
  src/server\mod_wsgi.c(1483): warning C4244: 'function': conversion from '__int64' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1491): warning C4244: 'function': conversion from 'apr_off_t' to 'std::apr_size_t', possible loss of data
  src/server\mod_wsgi.c(1514): warning C4244: 'function': conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1578): warning C4244: 'function': conversion from '__int64' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1624): warning C4244: 'function': conversion from 'apr_off_t' to 'std::apr_size_t', possible loss of data
  src/server\mod_wsgi.c(1653): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1657): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1670): warning C4244: 'function': conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1689): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1715): warning C4244: 'function': conversion from '__int64' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1757): warning C4244: 'function': conversion from 'apr_off_t' to 'std::apr_size_t', possible loss of data
  src/server\mod_wsgi.c(1786): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1790): warning C4244: 'function': conversion from 'apr_off_t' to 'std::size_t', possible loss of data
  src/server\mod_wsgi.c(1798): warning C4244: 'function': conversion from '__int64' to 'Py_ssize_t', possible loss of data
  src/server\mod_wsgi.c(1814): warning C4244: 'function': conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_apache.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_apache.obj
  wsgi_apache.c
  c:\python36\include\pyconfig.h(321): warning C4005: 'PLATFORM': macro redefinition
  c:\apache24\include\os.h(44): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_buckets.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_buckets.obj
  wsgi_buckets.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_convert.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_convert.obj
  wsgi_convert.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_daemon.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_daemon.obj
  wsgi_daemon.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_interp.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_interp.obj
  wsgi_interp.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_logger.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_logger.obj
  wsgi_logger.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_memory.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_memory.obj
  wsgi_memory.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_metrics.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_metrics.obj
  wsgi_metrics.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_restrict.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_restrict.obj
  wsgi_restrict.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_server.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_server.obj
  wsgi_server.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_stream.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_stream.obj
  wsgi_stream.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_thread.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_thread.obj
  wsgi_thread.c
  c:\apache24\include\os.h(44): warning C4005: 'PLATFORM': macro redefinition
  c:\python36\include\pyconfig.h(321): note: see previous definition of 'PLATFORM'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Apache24/include -IC:\Apache24\htdocs\venv\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/server\wsgi_validate.c /Fobuild\temp.win32-3.6\Release\src/server\wsgi_validate.obj
  wsgi_validate.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Apache24\htdocs\venv\libs /LIBPATH:c:\python36\libs /LIBPATH:c:\python36 /LIBPATH:C:\Apache24\htdocs\venv\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86" /EXPORT:PyInit_mod_wsgi build\temp.win32-3.6\Release\src/server\mod_wsgi.obj build\temp.win32-3.6\Release\src/server\wsgi_apache.obj build\temp.win32-3.6\Release\src/server\wsgi_buckets.obj build\temp.win32-3.6\Release\src/server\wsgi_convert.obj build\temp.win32-3.6\Release\src/server\wsgi_daemon.obj build\temp.win32-3.6\Release\src/server\wsgi_interp.obj build\temp.win32-3.6\Release\src/server\wsgi_logger.obj build\temp.win32-3.6\Release\src/server\wsgi_memory.obj build\temp.win32-3.6\Release\src/server\wsgi_metrics.obj build\temp.win32-3.6\Release\src/server\wsgi_restrict.obj build\temp.win32-3.6\Release\src/server\wsgi_server.obj build\temp.win32-3.6\Release\src/server\wsgi_stream.obj build\temp.win32-3.6\Release\src/server\wsgi_thread.obj build\temp.win32-3.6\Release\src/server\wsgi_validate.obj /OUT:build\lib.win32-3.6\mod_wsgi\server\mod_wsgi.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\src/server\mod_wsgi.cp36-win32.lib C:\Apache24\htdocs\venv\Scripts/libs/python36.lib C:\Apache24/lib/libhttpd.lib C:\Apache24/lib/libapr-1.lib C:\Apache24/lib/libaprutil-1.lib C:\Apache24/lib/libapriconv-1.lib
  LINK : fatal error LNK1181: cannot open input file 'C:\Apache24\htdocs\venv\Scripts/libs/python36.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1181
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi

**Comment by GrahamDumpleton** [comment] 2020-02-11 22:40
Try:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

**Comment by antoniovazquezblanco** [comment] 2020-02-12 09:11
Duplicate of https://github.com/GrahamDumpleton/mod_wsgi/issues/506

**Closed** 2020-02-12 23:19 UTC
