### ISSUE TITLE
Help for building with buildroot

### ISSUE THREAD

**Issue by MatthiasRoelandts** [GrahamDumpleton/mod_wsgi#323] opened 2018-05-30 13:41 UTC
Hello, I'm trying to install mod_wsgi on my raspberry pi.
I currently have build everything with busybox (buildroot).
Now I would like to include mod_wsgi on it, I followed the buildroot manual but are not able to make it work. [buildroot manual](http://nightly.buildroot.org/manual.pdf)
Currently I have this as `mod_wsgi.mk`
```
MOD_WSGI_VERSION = 4.6.4
MOD_WSGI_SOURCE = mod_wsgi-$(LIBFOO_VERSION).tar.gz
MOD_WSGI_SITE = $(call github,GrahamDumpleton,mod_wsgi,$(MOD_WSGI_VERSION))

define MOD_WSGI_BUILD_CMDS
	$(TARGET_MAKE_ENV)
endef

define MOD_WSGI_INSTALL_TARGET_CMDS
	$(INSTALL)
endef

$(eval $(generic-package))
```
Any help?

**Comment by GrahamDumpleton** [comment] 2018-05-31 00:09
Can you use ``pip install`` on that system?

If so, use that method of installation.

https://pypi.org/project/mod_wsgi/

**Comment by MatthiasRoelandts** [comment] 2018-05-31 06:44
Unfortunately no...
But even if, that would not be a wanted solution because then it would not be installed on the image after build and you would have to install it manually each time.

**Comment by GrahamDumpleton** [comment] 2018-05-31 11:07
If you can't do a ``pip install``, because I know nothing about the ``buildroot`` system, you are going to have to at least explain what the problem is when you say "not able to make it work". What does it fail to do? Do you get errors?

**Comment by GrahamDumpleton** [comment] 2018-06-29 01:47
Closing as no followup on what was meant by "not able to make it work".

FWIW, the ``mod_wsgi.mk`` has one obvious error in it of using ``LIBFOO_VERSION`` when should be ``MOD_WSGI_VERSION``.

**Closed by GrahamDumpleton** 2018-06-29 01:47 UTC
