### ISSUE TITLE
Redirect to ssl behind a Load Balancer

### ISSUE THREAD

**Issue by jakobholmelund** [GrahamDumpleton/mod_wsgi#86] opened 2015-08-06 10:27 UTC
I was wondering how to redirect all users to https. From what i could find, the prefered solution is to use something like this

NameVirtualHost *:80
<VirtualHost *:80>
   ServerName mysite.example.com
   DocumentRoot /usr/local/apache2/htdocs 
   Redirect permanent / https://mysite.example.com/
</VirtualHost>

<VirtualHost _default_:443>
   ServerName mysite.example.com
  DocumentRoot /usr/local/apache2/htdocs
  SSLEngine On
 # etc...
</VirtualHost>

And another solution is to use something like

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}

Since i'm behind a preconfigured Load Balancer, i'm not even sure if i'm supposed to use Apache for this. Right now, i'm using --include-file= and i can't seem to get any of the solutions to work. Am i doing something totally wrong ?

**Comment by GrahamDumpleton** [comment] 2015-08-06 12:20
Since you mentioned ``--include-file`` I am presuming you are using ``mod_wsgi-express``. If that is the case and you are using the ``--https-port`` option and appropriate ``--ssl-certificate-*`` options, then all you need to do to enforce a HTTPS only site is use the ``--https-only`` option.

When you use that option, ``mod_wsgi-express`` will automatically set up the required configuration to have any access to the ``http`` URL redirected to the ``https`` URL for the same site.

Try the ``--https-only`` option and if you cannot get that to work, then provide the full command line option you are using for ``mod_wsgi-express`` so I can see how you are running it.

**Comment by jakobholmelund** [comment] 2015-08-06 12:57
Yes, you are correct. I'm using mod_wsgi-express. But i'm using it behind an external load balancer that holds the certificate and everything is working great. All i need is automatic redirection from http to https for all requests. i'll give the --https-only a shot. Thank's for a quick reply.

**Comment by jakobholmelund** [comment] 2015-08-06 14:59
Hmm doesn't seem to work.. I will have time to see what's going on later tonight..

**Comment by GrahamDumpleton** [comment] 2015-08-06 20:32
Okay, if this is behind a front end which handles SSL and the proxies will be different.

What HTTP header does the front end set so the back end knows what protocol scheme was used for the original request?

If you don't know what I mean then have a read of my post about proxying at:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html

I mention the issue of secure connections in it.

Once I know what the header is, then can suggest something.

**Comment by jakobholmelund** [comment] 2015-08-06 21:40
From the documentation:

Target proxies terminate HTTP/HTTPS connections from clients, and are referenced by one or more global forwarding rules and route the incoming requests to a URL map.

The proxies set HTTP request/response headers as follows:

Via: 1.1 google (requests and responses)
X-Forwarded-Proto: [http | https] (requests only)
X-Forwarded-For: <client IP(s)>, <global forwarding rule external IP> (requests only)
The client IP part can be a comma-separated list of IP addresses depending on the X-Forwarded-For entries appended by the intermediaries the client is traveling through. The first element in the <client IP(s)> section shows the origin address.

So i think it uses the X-Forwarded-Proto: [http | https] to tell the servers behind it whether it's http or https .

**Comment by GrahamDumpleton** [comment] 2015-08-06 23:13
What you want to do in the rewrite rule is consult ``HTTP_X_FORWARDED_PROTO``, checking for it being ``https``. In that case redirect.

I haven't got time right now to work out the exact configuration required, but you might have a play first.

What I should look at is having ``--https-only`` be smarter. Although it works in Apache configuration, have a fallback in the WSGI application wrapper which will also redirect at Python level when WSGI environ is adjusted as a result of the proxy. In fact when using a proxy, that may only be the way that works right now and doing as rewrite rule may not work.

**Comment by jakobholmelund** [comment] 2015-08-07 08:47
So something like this ?

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP:http_x_forwarded_proto} != https
RewriteCond %{HTTP:http_x_forwarded_proto} != HTTPS
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by jakobholmelund** [comment] 2015-08-07 09:14
Hmm doing it with django produces this error and 

```
This webpage has a redirect loop

ERR_TOO_MANY_REDIRECTS
```

and 

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP:X-Forwarded-Proto} !https [NC]
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

seems to have no effect

**Comment by jakobholmelund** [comment] 2015-08-07 09:15
Do i need to do something in apache to send X-Forwarded-Proto header to the WSGI app ?

**Comment by GrahamDumpleton** [comment] 2015-08-09 12:09
Sorry for the delay. I can't really find a way one could do it at the Apache config level by trying to include additional Apache configuration snippets using ``--inlude-file``.

It will not work as what is being included using that option is simply stuck at the end of the generated file and isn't able to be inserted at the correct place, even if that will help.

The only way at this point until I can integrate something into mod_wsgi-express itself is to do the following in the WSGI application.

```
def application_redirect(environ, start_response):
    headers = []
    headers.append(('Location', 'https://%s%s%s' % (
            environ.get('HTTP_HOST'), environ.get('SCRIPT_NAME'),
            environ.get('PATH_INFO'))))
    start_response('302 OK', headers)
    yield ''

def application_normal(environ, start_response):
    ... Your original WSGI application entry point.

def application(environ, start_response):
    if environ.get('HTTP_X_FORWARDED_PROTO', 'http') != 'https':
        return application_redirect(environ, start_response)
    else:
        return application_normal(environ, start_response)
```

This presumes the front end is using HTTPS port 443. If it wasn't for some reason the URL in the ``Location`` response header returned would also need to include the port used for the HTTPS connection.

The code also presumes that ``HTTP_X_FORWARDED_PROTO`` is actually set by the front end to ``https`` when the request comes via HTTPS.

I will have to think about the best way of allowing HTTPS redirection when specifically behind a proxy and relying on trusted proxy headers.

**Comment by GrahamDumpleton** [comment] 2015-08-10 00:04
If using mod_wsgi-express with option:

```
--trust-proxy-header X-Forwarded-Proto
```

then that is actually better written as:

```
def application(environ, start_response):
    if environ.get('wsgi.url_scheme', 'http') != 'https':
        return application_redirect(environ, start_response)
    else:
        return application_normal(environ, start_response)
```

Anyway, contemplating adding to mod_wsgi-express the options:

```
--proxy-https-port nnn
--proxy-https-only
```

The first one is optional and would on;y be used if front end would be using a port other than 443 for HTTPS.

The second when used in conjunction with ``--trust-proxy-header`` options to identify which are trusted proxy headers, would cause the redirection to ``https`` if the URL scheme wasn't ``https``.

If possible this could be done in mod_wsgi core itself, and so allowed via a directive in the Apache configuration and thus usable even if using mod_wsgi directly and not via mod_wsgi-express. Otherwise would be implemented in mod_wsgi-express in its WSGI middleware wrappers that it sticks around your actual application. That means that it does have to drop into Python code though.

**Comment by jakobholmelund** [comment] 2015-08-10 08:05
Hey Graham. I'll try it out later today. Again thank you so much for your time.

**Comment by jakobholmelund** [comment] 2015-08-12 21:22
It seems to work.. If anyone using Django is reading this, my wsgi.py looks like this


```
"""
WSGI config for config project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.7/howto/deployment/wsgi/
"""

import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.prod")

from django.core.wsgi import get_wsgi_application

django_application = get_wsgi_application()

def application_redirect(environ, start_response):
    headers = []
    headers.append(('Location', 'https://%s%s%s' % (
            environ.get('HTTP_HOST'), environ.get('SCRIPT_NAME'),
            environ.get('PATH_INFO'))))
    start_response('302 OK', headers)
    yield ''


def application_normal(environ, start_response):
    return django_application(environ, start_response)


def application(environ, start_response):
    if environ.get('wsgi.url_scheme', 'http') != 'https':
        return application_redirect(environ, start_response)
    else:
        return application_normal(environ, start_response)
```

and i added these parameters to mod_wsgi-express

```
--https-only 
--trust-proxy-header", "X-Forwarded-Proto
```

**Comment by jakobholmelund** [comment] 2015-08-19 13:36
Hmm never really got this working.. Any news with the implementation ? Another thing is redirection from naked domain to www or the other way around... As far as i can see there is no setting for that either

**Comment by GrahamDumpleton** [comment] 2015-08-20 00:33
Redirection from ``domain.com`` to ``www.domain.com`` should be automatic if you have set ``--server-name`` to ``www.domain.com``.

```
    optparse.make_option('--server-name', default=None, metavar='HOSTNAME',
            help='The primary host name of the web server. If this name '
            'starts with \'www.\' then an automatic redirection from the '
            'parent domain name to the \'www.\' server name will created.'),
```

Normally you would only use ``--server-name`` if terminating SSL. Try it even if not and let me know if doesn't work. Can't try myself right now.

**Comment by jakobholmelund** [comment] 2015-08-20 10:28
Hmm it seems that the setting makes my server unreachable.. This external loadbalancer is really creating some problems :/

**Comment by GrahamDumpleton** [comment] 2015-08-20 10:31
I forgot about the load balancer. In setting that, the 'Host' header would need to be transferred through as it was originally. Likely the load balancer does not do that. What is the value of 'Host' header as seen by the application when you don't set that? I presume it is different to what you are using with ``--server-name``.

**Comment by jakobholmelund** [comment] 2015-08-20 10:33
As far is a i have understood, the load balancer sends a chain of the hosts it's gone through with X-Forwarded-For . Also it seems that the load balancer makes no guarantees as to what the Host will bee, probably some random ip .

**Comment by GrahamDumpleton** [comment] 2015-08-20 10:35
Yep. The ``--server-name`` sets up an Apache ``VirtualHost`` which works off the ``Host`` header and pays no attention to ``X-Forwarded-For``. :-(

Again comes down to having to do it in a WSGI middleware wrapper.

**Comment by jakobholmelund** [comment] 2015-08-20 10:37
dang.. :/ It will probably take some time to get into express i guess.. It seems there are quite a few implementations if you google it. But i know it's always harder to make general purpose..

**Comment by GrahamDumpleton** [comment] 2015-08-20 12:04
It doesn't necessarily need to take long to get changes into mod_wsgi-express. The work itself isn't that much. What I spend so much time on is coming up with a sensible naming system for the command line options and what it then triggers. :-)

To summarise what we are after, it is:

1. When behind a proxy which accepts both HTTP and HTTPS, and then forwards as HTTP only, have a way of forcing redirection from HTTP to HTTPS from the backend application.

2. When behind a proxy which accepts both domain.com and www.domain.com, have a way of forcing domain.com to www.domain.com from the backend application.

**Comment by jakobholmelund** [comment] 2015-08-20 12:17
Hmm i think the two headers mentioned earlier are pretty standard at least
both Amazon and Google and a couple others I've seen implement them. How
about just checking for them and decide what to do based on their values ?
That way you won't have to name any parameters :) then you can always add
parameter options later if someone is using some obscure load balancer and
needs it.

**Comment by GrahamDumpleton** [comment] 2015-08-20 12:46
The names of the headers isn't the issue as the way the ``--trust-proxy-header`` option is set up you give it the name of the header to believe. Internal mod_wsgi knows what all the typically used header names for things and what they mean and normalises it into the appropriate WSGI environ settings. You can see the code for that starting at:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/mod_wsgi.c#L12847

The issue is that that is applied after where HTTP/HTTPS and domain.com/www.domain.com redirections are done in due to Apache configuration for normal case where no proxy is involved and that isn't readily able to be changed.

Thus the redirections need to be done in the WSGI application wrapper that mod_wsgi express uses around your WSGI application. I just need separate options to enable it being done based on the trusted values coming from the proxy.

I was going to have a go at the HTTPS redirection yesterday, but got bogged down in some other stuff and then been out most of today. Am going to think about best way of doing the options overnight and see if can get something implemented tomorrow.

**Comment by jakobholmelund** [comment] 2015-08-20 13:01
Sounds good, i'm just happy that you've been so helpful and quick to respond.

I see where you are going. I don't know why i had in my head that it was the Apache config that needed to be changed, i had the idea, that it would be best for Performance if Apache handled it all. looking forward to see what you come up with.

**Comment by jakobholmelund** [comment] 2015-08-26 14:18
It's pretty weird, it seems like every attempt i make at achieving this through the wsgi app (Django) or wsgi wrapper (wsgi.py) ends up in the server not being reachable.. I would like to think that i've tried everything, but i probably haven't.

**Comment by GrahamDumpleton** [comment] 2015-08-27 00:36
Can you use:

* https://code.google.com/p/modwsgi/wiki/DebuggingTechniques#Displaying_Request_Environment

to at least capture the WSGI request environment so I can see what is sent and show exactly what your middleware is doing.

Even better use:

* https://code.google.com/p/modwsgi/wiki/DebuggingTechniques#Tracking_Request_and_Response

to also capture all the response headers.

**Comment by jakobholmelund** [comment] 2015-08-27 11:52
Sure, i'll give it a spin right away..

**Comment by jakobholmelund** [comment] 2015-08-27 13:47
Well i was able to get the important stuff from the logging to terminal..

here is a typical request, as seen by the wsgi wrapper

[Thu Aug 27 13:35:34.350223 2015] [wsgi:error]   ('REQUEST',
[Thu Aug 27 13:35:34.351281 2015] [wsgi:error]    {'CONTEXT_DOCUMENT_ROOT': '/tmp/mod_wsgi-localhost:80:0/htdocs',
[Thu Aug 27 13:35:34.351333 2015] [wsgi:error]     'CONTEXT_PREFIX': '',
[Thu Aug 27 13:35:34.351424 2015] [wsgi:error]     'DOCUMENT_ROOT': '/tmp/mod_wsgi-localhost:80:0/htdocs',
[Thu Aug 27 13:35:34.351501 2015] [wsgi:error]     'GATEWAY_INTERFACE': 'CGI/1.1',
[Thu Aug 27 13:35:34.351578 2015] [wsgi:error]     'HTTP_ACCEPT': 'application/json, text/plain, */*',
[Thu Aug 27 13:35:34.351648 2015] [wsgi:error]     'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
[Thu Aug 27 13:35:34.351718 2015] [wsgi:error]     'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,da;q=0.6',
[Thu Aug 27 13:35:34.351765 2015] [wsgi:error]     'HTTP_CONNECTION': 'Keep-Alive',
[Thu Aug 27 13:35:34.351916 2015] [wsgi:error]     'HTTP_COOKIE': '__unam=7639673-14fefefed6632224f-6af19bf7-18; sessionid=m76nqcascazf1gtrgew71e14v5m; csrftoken=74id6KcnPtfwefweM3YcxtXs; _ga=GA1.2.15185434342436.1431938668',
[Thu Aug 27 13:35:34.351974 2015] [wsgi:error]     'HTTP_HOST': 'www.sonofatailor.com',
[Thu Aug 27 13:35:34.352057 2015] [wsgi:error]     'HTTP_REFERER': 'http://www.sonofatailor.com/',
[Thu Aug 27 13:35:34.352152 2015] [wsgi:error]     'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
[Thu Aug 27 13:35:34.352213 2015] [wsgi:error]     'HTTP_VIA': '1.1 google',
[Thu Aug 27 13:35:34.352285 2015] [wsgi:error]     'HTTP_X_CSRFTOKEN': '74id6Kfewfewf9zwv6uM3YcxtXs',
[Thu Aug 27 13:35:34.352360 2015] [wsgi:error]     'HTTP_X_FORWARDED_FOR': '94.18.225.106, 107.178.250.104',
[Thu Aug 27 13:35:34.352408 2015] [wsgi:error]     'HTTP_X_FORWARDED_PROTO': 'http',
[Thu Aug 27 13:35:34.352519 2015] [wsgi:error]     'PATH_INFO': '/oscarapi/basket/',
[Thu Aug 27 13:35:34.352632 2015] [wsgi:error]     'PATH_TRANSLATED': '/tmp/mod_wsgi-localhost:80:0/htdocs/basket/',
[Thu Aug 27 13:35:34.352723 2015] [wsgi:error]     'QUERY_STRING': '',
[Thu Aug 27 13:35:34.352803 2015] [wsgi:error]     'REMOTE_ADDR': '10.240.184.199',
[Thu Aug 27 13:35:34.352867 2015] [wsgi:error]     'REMOTE_PORT': '49892',
[Thu Aug 27 13:35:34.352980 2015] [wsgi:error]     'REQUEST_METHOD': 'GET',
[Thu Aug 27 13:35:34.353062 2015] [wsgi:error]     'REQUEST_SCHEME': 'http',
[Thu Aug 27 13:35:34.353125 2015] [wsgi:error]     'REQUEST_URI': '/oscarapi/basket/',
[Thu Aug 27 13:35:34.353210 2015] [wsgi:error]     'SCRIPT_FILENAME': '/tmp/mod_wsgi-localhost:80:0/htdocs/oscarapi',
[Thu Aug 27 13:35:34.353255 2015] [wsgi:error]     'SCRIPT_NAME': '',
[Thu Aug 27 13:35:34.353314 2015] [wsgi:error]     'SERVER_ADDR': '10.4.1.110',
[Thu Aug 27 13:35:34.353382 2015] [wsgi:error]     'SERVER_ADMIN': '[no address given]',
[Thu Aug 27 13:35:34.353449 2015] [wsgi:error]     'SERVER_NAME': 'www.sonofatailor.com',
[Thu Aug 27 13:35:34.353494 2015] [wsgi:error]     'SERVER_PORT': '80',
[Thu Aug 27 13:35:34.353551 2015] [wsgi:error]     'SERVER_PROTOCOL': 'HTTP/1.1',
[Thu Aug 27 13:35:34.353609 2015] [wsgi:error]     'SERVER_SIGNATURE': '',
[Thu Aug 27 13:35:34.353655 2015] [wsgi:error]     'SERVER_SOFTWARE': 'Apache',
[Thu Aug 27 13:35:34.353735 2015] [wsgi:error]     'apache.version': (2, 4, 10),
[Thu Aug 27 13:35:34.353796 2015] [wsgi:error]     'mod_wsgi.application_group': '',
[Thu Aug 27 13:35:34.353863 2015] [wsgi:error]     'mod_wsgi.callable_object': 'handle_request',
[Thu Aug 27 13:35:34.353945 2015] [wsgi:error]     'mod_wsgi.daemon_connects': '1',
[Thu Aug 27 13:35:34.353990 2015] [wsgi:error]     'mod_wsgi.daemon_restarts': '0',
[Thu Aug 27 13:35:34.354055 2015] [wsgi:error]     'mod_wsgi.daemon_start': '1440682534348867',
[Thu Aug 27 13:35:34.354112 2015] [wsgi:error]     'mod_wsgi.enable_sendfile': '0',
[Thu Aug 27 13:35:34.354193 2015] [wsgi:error]     'mod_wsgi.handler_script': '/tmp/mod_wsgi-localhost:80:0/handler.wsgi',
[Thu Aug 27 13:35:34.354255 2015] [wsgi:error]     'mod_wsgi.listener_host': '',
[Thu Aug 27 13:35:34.354301 2015] [wsgi:error]     'mod_wsgi.listener_port': '80',
[Thu Aug 27 13:35:34.354359 2015] [wsgi:error]     'mod_wsgi.path_info': '/basket/',
[Thu Aug 27 13:35:34.354427 2015] [wsgi:error]     'mod_wsgi.process_group': 'localhost:80',
[Thu Aug 27 13:35:34.354496 2015] [wsgi:error]     'mod_wsgi.queue_start': '1440682534348784',
[Thu Aug 27 13:35:34.354588 2015] [wsgi:error]     'mod_wsgi.request_handler': 'wsgi-handler',
[Thu Aug 27 13:35:34.354659 2015] [wsgi:error]     'mod_wsgi.request_start': '1440682534348292',
[Thu Aug 27 13:35:34.354707 2015] [wsgi:error]     'mod_wsgi.script_name': '/oscarapi',
[Thu Aug 27 13:35:34.354763 2015] [wsgi:error]     'mod_wsgi.script_reloading': '1',
[Thu Aug 27 13:35:34.354829 2015] [wsgi:error]     'mod_wsgi.script_start': '1440682534348942',
[Thu Aug 27 13:35:34.354915 2015] [wsgi:error]     'mod_wsgi.version': (4, 4, 14),
[Thu Aug 27 13:35:34.354981 2015] [wsgi:error]     'wsgi.errors': <mod_wsgi.Log object at 0x7fe2576be3d8>,
[Thu Aug 27 13:35:34.355027 2015] [wsgi:error]     'wsgi.file_wrapper': <type 'mod_wsgi.FileWrapper'>,
[Thu Aug 27 13:35:34.355086 2015] [wsgi:error]     'wsgi.input': <mod_wsgi.Input object at 0x7fe2526d4940>,
[Thu Aug 27 13:35:34.355150 2015] [wsgi:error]     'wsgi.multiprocess': False,
[Thu Aug 27 13:35:34.355195 2015] [wsgi:error]     'wsgi.multithread': True,
[Thu Aug 27 13:35:34.355251 2015] [wsgi:error]     'wsgi.run_once': False,
[Thu Aug 27 13:35:34.355309 2015] [wsgi:error]     'wsgi.url_scheme': 'http',
[Thu Aug 27 13:35:34.355384 2015] [wsgi:error]     'wsgi.version': (1, 0)})

**Comment by jakobholmelund** [comment] 2015-08-31 12:08
Ok.. I finally got this working by analysing the logs.. The solution that works looks like this

wsgi.py

```
"""
WSGI config for config project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.7/howto/deployment/wsgi/
"""

import os
import djcelery
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.prod")

djcelery.setup_loader()

from django.core.wsgi import get_wsgi_application

#application = get_wsgi_application()

django_application = get_wsgi_application()
#
def application_redirect(environ, start_response, http_host):
    headers = []
    headers.append(('Location', 'https://%s%s%s' % (
            http_host, environ.get('SCRIPT_NAME'),
            environ.get('PATH_INFO'))))
    start_response('302 OK', headers)
    yield ''


def application_normal(environ, start_response):
    return django_application(environ, start_response)


def application(environ, start_response):
    http_host = environ.get('HTTP_HOST')

    redirect_naked = False
    is_soat_host = False

    if "soat.com" in http_host:
        is_soat_host = True
        if "www" not in http_host:
            http_host = "www.%s" % http_host
            redirect_naked = True

    if (environ.get('wsgi.url_scheme', 'http') != 'https' and is_soat_host) or redirect_naked:
        #return django_application(environ, start_response)
        return application_redirect(environ, start_response, http_host)
    else:
        return django_application(environ, start_response)

```

Because i have a lot of health checks that seems to hit apache with seemingly random ip's i had to put in a check to see if the host name was correct. I also build in redirection from naked domain to www

**Comment by pburkholder** [comment] 2016-08-15 20:34
Thanks for this discussion -- it really helped me out with a Django app in Pivotal CloudFoundry (see: https://support.run.pivotal.io/entries/82035305-How-do-I-force-my-users-to-use-HTTPS-). Here's how I'm doing this:

```
import os, sys
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "siteapp.settings")
from django.core.wsgi import get_wsgi_application

django_application = get_wsgi_application()

if os.getenv('VCAP_APPLICATION'):
    from whitenoise.django import DjangoWhiteNoise
    django_application = DjangoWhiteNoise(django_application)

def application_redirect(environ, start_response, http_host):
    headers = []
    headers.append(('Location', 'https://%s%s%s' % (
            http_host, environ.get('SCRIPT_NAME'),
            environ.get('PATH_INFO'))))
    start_response('302 OK', headers)
    yield ''

def application(environ, start_response):
    http_host = environ.get('HTTP_HOST')

    if (environ.get('wsgi.url_scheme', 'http') != 'https') and os.getenv('VCAP_APPLICATION'):
        return application_redirect(environ, start_response, http_host)
    else:
        return django_application(environ, start_response)
```

Somewhat shorter, and removes the dead code in `def application_normal...`

**Comment by GrahamDumpleton** [comment] 2018-01-23 11:10
I am going to finally close this without making any changes. Because proxies may be implemented differently, use of a custom middleware may well be the best solution. Would have to see more instances of this being a problem before consider trying to make automatic redirection when behind a proxy, in mod_wsgi-express.

**Closed by GrahamDumpleton** 2018-01-23 11:10 UTC
