### ISSUE TITLE
"Truncated or oversized response headers received from daemon process" with postgresql

### ISSUE THREAD

**Issue by sidark** [GrahamDumpleton/mod_wsgi#390] opened 2019-01-10 10:22 UTC
Hello,
At the beginning I would like to thank you for your amazing work, I use that from the beginning of my programming adventure and it helped me a lot.
But now i need your help with error that my django site giving:
```
[Thu Jan 10 11:15:34.815599 2019] [wsgi:info] [pid 676] mod_wsgi (pid=676): Starting process 'monitoring' with uid=33, gid=33 and threads=15.
[Thu Jan 10 11:15:34.816009 2019] [wsgi:info] [pid 676] mod_wsgi (pid=676): Python home /var/www/monitoring/monitoringenv.
[Thu Jan 10 11:15:34.816053 2019] [wsgi:info] [pid 676] mod_wsgi (pid=676): Initializing Python.  
[Thu Jan 10 11:15:34.833421 2019] [wsgi:info] [pid 676] mod_wsgi (pid=676): Attach interpreter ''.
[Thu Jan 10 11:15:34.843520 2019] [wsgi:info] [pid 676] mod_wsgi (pid=676): Adding '/var/www/monitoring' to path.
[Thu Jan 10 11:15:34.848976 2019] [wsgi:info] [pid 676] mod_wsgi (pid=676): Imported 'mod_wsgi'.
[Thu Jan 10 11:15:37.484774 2019] [wsgi:info] [pid 676] [remote 213.92.137.106:50499] mod_wsgi (pid=676, process='monitoring', application=''): Loading Python script file '/var/www/monitoring/monitoring/wsgi.py'.
[Thu Jan 10 11:15:37.970281 2019] [wsgi:error] [pid 676] monitor (pid=676): Starting stack trace monitor.
[Thu Jan 10 11:20:05.019687 2019] [wsgi:error] [pid 676] 
[Thu Jan 10 11:20:05.022411 2019] [wsgi:error] [pid 676] # ProcessId: 676
[Thu Jan 10 11:20:05.022423 2019] [wsgi:error] [pid 676] 
[Thu Jan 10 11:20:05.022434 2019] [wsgi:error] [pid 676] # ThreadID: 140576022329088
[Thu Jan 10 11:20:05.024035 2019] [wsgi:error] [pid 676] File: "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
[Thu Jan 10 11:20:05.024044 2019] [wsgi:error] [pid 676]   self._bootstrap_inner()
[Thu Jan 10 11:20:05.024050 2019] [wsgi:error] [pid 676] File: "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[Thu Jan 10 11:20:05.024056 2019] [wsgi:error] [pid 676]   self.run()
[Thu Jan 10 11:20:05.024069 2019] [wsgi:error] [pid 676] File: "/usr/lib/python3.6/threading.py", line 864, in run
[Thu Jan 10 11:20:05.024077 2019] [wsgi:error] [pid 676]   self._target(*self._args, **self._kwargs)
[Thu Jan 10 11:20:05.024085 2019] [wsgi:error] [pid 676] File: "/var/www/monitoring/monitoring/wsgi.py", line 66, in _monitor
[Thu Jan 10 11:20:05.024094 2019] [wsgi:error] [pid 676]   _stacktraces()
[Thu Jan 10 11:20:05.024105 2019] [wsgi:error] [pid 676] File: "/var/www/monitoring/monitoring/wsgi.py", line 41, in _stacktraces
[Thu Jan 10 11:20:05.024115 2019] [wsgi:error] [pid 676]   for filename, lineno, name, line in traceback.extract_stack(stack):
[Thu Jan 10 11:20:24.457384 2019] [wsgi:error] [pid 32340] [client 213.92.137.106:50695] Truncated or oversized response headers received from daemon process 'monitoring': /var/www/monitoring/monitoring/wsgi.py, referer: http://monitoring.domain.com/login/?next=/
[Thu Jan 10 11:20:25.097143 2019] [core:notice] [pid 16346] AH00052: child pid 676 exit signal Segmentation fault (11)
[Thu Jan 10 11:20:25.097196 2019] [wsgi:info] [pid 16346] mod_wsgi (pid=676): Process 'monitoring' has died, deregister and restart it.
[Thu Jan 10 11:20:25.097202 2019] [wsgi:info] [pid 16346] mod_wsgi (pid=676): Process 'monitoring' terminated by signal 11
[Thu Jan 10 11:20:25.097220 2019] [wsgi:info] [pid 16346] mod_wsgi (pid=676): Process 'monitoring' has been deregistered and will no longer be monitored.
```

Setting of my virtualhost: 
```
LoadModule wsgi_module "/var/www/monitoring/monitoringenv/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/var/www/monitoring/monitoringenv"

<VirtualHost *:80>

        ServerName monitoring.domain.com 
        ServerAdmin admin@domain.com

  
        WSGIDaemonProcess monitoring python-home=/var/www/monitoring/monitoringenv python-path=/var/www/monitoring
        WSGIProcessGroup monitoring
        WSGIScriptAlias / /var/www/monitoring/monitoring/wsgi.py process-group=monitoring

        <Directory /var/www/monitoring/monitoring>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        Alias /static/ /var/www/monitoring/static/
        <Directory /var/www/monitoring/static>
                Require all granted
        </Directory>

</VirtualHost>
```

I using: 
- Django==2.1.2
- mod-wsgi==4.6.5
- psycopg2-binary==2.7.5
- Ubuntu 16.04
- Apache 2.4.18
- Postgresql 9.5

The site stopped works properly suddenly - after 2 month of working without any breaks. 
What's more the site doesn't work only on that pages where some data from database is taken.

What i did in order to solve that, or get usefull informations:
- On runserver, also mod_wsgi-express it works well,
- Tested on mysql and sqlite3: on these databases it works well,
- Switched to debug mode: no changes,
- Updated postgresql from 9.5 to 10.0: no changes,
- Increased default limits of postgresql: no changes,
- Deprecated mod-wsgi to version 4.2: no changes,
- Added `WSGIApplicationGroup %{GLOBAL}`: no changes,
- Added `application-group=%{GLOBAL}` to `WSGIScriptAlias`: no changes,
- Added `processes` and `threads` to `WSGIDaemonProcess`, tried multiple values: no changes,
- Tried to login on django admin to ensure my code is not guilty: login page loaded, but after submitting login form same error,
- Changed `psycopg2-binary` to `psycopg2`: no changes

Hopefully that broken site is my internal site, but i have many of commercial sites on different servers, and now i'm afraid of another sites problems. Please advice.

**Comment by sidark** [comment] 2019-01-10 10:36
Yes i have mod_ssl enabled and using HTTPS, i disabled it completely moment ago to check - no changes, same error.

No i didn't performed any actions on that server before error, also automatic updates is disabled there, the error come out of the blue...

**Comment by GrahamDumpleton** [comment] 2019-01-10 10:41
When you disable the mod_ssl module so it wasn't loaded, did you do a complete stop of Apache and then a start? Doing a reload/restart isn't going to be enough to evict the SSL libraries and complete stop/start is probably needed.

Reason asking about this is that have seen issues where Apache was built with slightly different SSL libraries versions than Python, or some third party Python package. This can sometimes cause issues.

If the issue is reproducible, and you have gdb on the box, you can always follow steps in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

The steps are to attach gdb to the mod_wsgi daemon process and then trigger the request and see where it crashes.

**Comment by nottheend** [comment] 2019-03-23 15:09
Thanks for developing and greetings ;-)

The same issue happened also to another server, running centos7:
`Truncated or oversized response headers received from daemon process 'appname': /home/username/project/project/wsgi.py
`

- CentOS: 7.6
- django: 2.1.7
- Apache: 2.4.6 (CentOS)
- OpenSSL: 1.0.2k-fips
- mod_wsgi: 4.6.2 with Python 3.6

I also tried the mentioned solutions in this issue e.g. `WSGIApplicationGroup %{GLOBAL}` to apache configuration file, but no success.
Using `daemon mode` as mentioned on the [django documentiation page](https://docs.djangoproject.com/en/2.1/howto/deployment/wsgi/modwsgi/).

The project actually was working properly and served with `mod_wsgi` in `daemon mode`. After trying to enable SSL, the `500 internal server error`.

Reverting back all changes and stop and start apache didn't help.

Is there a way to solve this?

**Comment by nottheend** [comment] 2019-03-23 20:08
And thanks again for developing @GrahamDumpleton :-)

**Comment by GrahamDumpleton** [comment] 2019-03-23 21:32
Have you tried to capture a gdb stack trace as suggested? Unless someone can do this it is hard to work out why, if nothing else suggested worked.

The only other thing that didn't seem to be mentioned, was whether mod_php was also enabled in Apache. It can cause conflicts. If you are not using PHP, make sure it isn't enabled for Apache. Also mention whether you are using system versions of packages for Apache, mod_wsgi and Python, and if not where they came from and how/where they were installed.

**Comment by nottheend** [comment] 2019-03-24 16:34
I will try to capture a gdb stack trace, thanks.

`mod_php` is not enabled.
These are the installed versions and how they were installed:

```
# install apache
sudo yum install httpd
sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
# install python3.6
sudo yum -y install python36u python36u-setuptools python36u-devel python36u-pip
# install apache with correct modul of mod_wsgi to serve python
sudo yum -y install python36u-mod_wsgi
sudo pip3.6 install virtualenv
# creating virtual environment
python3.6 -m venv ~/venv
# activate virtual environment
source ~/venv/bin/activate
# install needed software
pip install -r requirements.txt
```
After that, some SELINUX permissions were granted to serve via `mod_wsgi`

**Comment by nottheend** [comment] 2019-03-25 13:12
_Journey continued:_

Through debugging via gdb I received a error-message:
`ModuleNotFoundError: No module named 'django'
`

Seemed that the virtual environment is not used correctly. Came across [stackoverflow](https://stackoverflow.com/questions/51049854/python-home-option-fails-when-attempting-to-configure-django-mod-wsgi-applicatio), but didn't seem to help due to slightly different error.

Setting up virtual environment again showed up an error, which I ignored firstly by using `sudo`:
```
(venv) [user@server ~]$ pip install mod_wsgi
Collecting mod_wsgi
 Using cached https://files.pythonhosted.org/packages/47/69/5139588686eb40053f8355eba1fe18a8bee94dc3efc4e36720c73e07471a/mod_wsgi-4.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_1csmbig/mod-wsgi/setup.py", line 168, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_1csmbig/mod-wsgi/

```

I am not able to install `mod_wsgi` in virtual environment without `sudo`-priviledge.
Probably installing it with `sudo` is not a good idea, because it will install `mod_wsgi` on the wrong path.

What is the best way to work around this error?

PS: Is there a better place to discuss this? Because I think this should not be the right place of discussion

**Comment by sidark** [comment] 2019-03-25 13:17
After days of trying every way i found - no results. Fortunately it was my development server so i could format whole server easily. After that i made exact 100% same setup as before and problem disappear...
I know it's not solution - @nottheend looking forward you to solve that mistery, if you will succeed please post the solution, i'm afraid of that error can appear on some of my production servers.

**Comment by nottheend** [comment] 2019-03-25 15:15
@sidark thanks for sharing.

Still not succeeded.
Last try: https://serverfault.com/questions/941341/django-2-1-deployment-on-centos-7-with-apache-mod-wsgi-python3-venv/941869

**Comment by nottheend** [comment] 2019-03-26 16:08
Setting option `memory-limit` for `WSGIDaemonProcess` directive according to https://github.com/GrahamDumpleton/mod_wsgi/issues/340#issuecomment-476451650

Fails with error-message:
```
[Tue Mar 26 16:14:01 2019] [wsgi:info] [pid 24874] mod_wsgi (pid=24874): Starting process 'appname' with uid=48, gid=48 and threads=15.
[Tue Mar 26 16:14:01 2019] [wsgi:crit] [pid 24874] mod_wsgi (pid=24874): Couldn't set memory limit of 2048 for process 'appname'.
```

According to the [documentation](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html) I made sure, that `setrlimit()` is implemented (using recent version of centos7).

Could the error be a hint for another problem?

Tried to set the memory limit to other values, no success either.

**Comment by nottheend** [comment] 2019-03-26 16:27
Finally I could make it to get a more proper error-message from `gdb`:

```
(gdb) cont
Continuing.
Detaching after fork from child process 8297.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fbf5c7f8700 (LWP 8266)]
0x00007fbf77100956 in __strcmp_sse2 () from /lib64/libc.so.6
```
[Full stack trace](https://gist.github.com/nottheend/a3678c7eda8881c485deb27a654a45b6)

Any ideas about it?

**Comment by GrahamDumpleton** [comment] 2019-03-27 08:47
Right now I am inclined to close this issue and make each of you start over and create new separate issues, because if you are different people with different problems, having one hijack an existing issue has just made things a mess and harder to follow. You should never ask about new problems on existing issues in the first place. I am seriously not sure what I am supposed to be trying to help with now since so many issues being asked about. Create separate issues for separate problems.

Al I can say is that for the very last comment with stack trace, it indicates a conflict with binaries compiled against different SSL libraries. This may be caused by using binary wheels for Python packages (eg. nassl) which were compiled against incompatible SSL libraries to what your system or Apache uses. Why are using nassl library? Can you stop using it?

**Comment by nottheend** [comment] 2019-03-27 10:26
This issue became messy, therefore I cleaned some comments here and opened [another issue #404](https://github.com/GrahamDumpleton/mod_wsgi/issues/404)

**Closed** 2020-02-17 00:25 UTC
