### ISSUE TITLE
[wsgi:error] ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by widon1104** [GrahamDumpleton/mod_wsgi#305] opened 2018-04-23 12:00 UTC
MY OS is ubuntu17.10 and I use firefox.

This is the **/var/log/apache2/error.log**

[Mon Apr 23 19:47:29.444863 2018] [wsgi:error] [pid 3149] ***************************** ['/home/widon/.local/lib/python3.6/site-packages', '/home/widon/python/mysite', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
[Mon Apr 23 19:47:29.445606 2018] [wsgi:error] [pid 3149] [client 127.0.0.1:59284] mod_wsgi (pid=3149): Failed to exec Python script file '/home/widon/python/mysite/mysite/wsgi.py'.
[Mon Apr 23 19:47:29.445716 2018] [wsgi:error] [pid 3149] [client 127.0.0.1:59284] mod_wsgi (pid=3149): Exception occurred processing WSGI script '/home/widon/python/mysite/mysite/wsgi.py'.
[Mon Apr 23 19:47:29.445902 2018] [wsgi:error] [pid 3149] [client 127.0.0.1:59284] Traceback (most recent call last):
[Mon Apr 23 19:47:29.445962 2018] [wsgi:error] [pid 3149] [client 127.0.0.1:59284]   File "/home/widon/python/mysite/mysite/wsgi.py", line 15, in <module>
[Mon Apr 23 19:47:29.445975 2018] [wsgi:error] [pid 3149] [client 127.0.0.1:59284]     from django.core.wsgi import get_wsgi_application
[Mon Apr 23 19:47:29.446018 2018] [wsgi:error] [pid 3149] [client 127.0.0.1:59284] **ModuleNotFoundError: No module named 'django'**

The sys.path is right, has django path in it('/home/widon/.local/lib/python3.6/site-packages')
I find out I must set the folder django to **777** to fix this problem.
**widon@widon-X555YI:~/.local/lib/python3.6/site-packages$ chmod 777 django/ -R**
**widon@widon-X555YI:~/.local/lib/python3.6/site-packages$ chmod 777 pytz -R**
widon@widon-X555YI:~/.local/lib/python3.6/site-packages$ service apache2 restart
Why I have to change the django folder  to 777? the default is 755, I think It's quite enough.
Is it a bug of mod_wsgi ?

**Comment by GrahamDumpleton** [comment] 2018-04-29 06:38
It should be sufficient to have it as ``0755``. The user that Apache runs your code as only needs read access.

Usually the problem is that your home directory is only ``0750``. Are you sure you didn't also change the permissions on your home directory as well?

**Comment by widon1104** [comment] 2018-04-30 06:36
widon@widon-X555YI:~$ ls / -lh
总用量 100K
drwxr-xr-x   4 root root 4.0K 10月 16  2017 home
the home directory is 0755，I never change it.I just change django and pytz directory to 0777 to solve my problem.

**Comment by GrahamDumpleton** [comment] 2018-04-30 07:14
I would suggest doing:

```
chmod 755 django/ -R
chmod 755 pytz -R
```

and see if it goes back to not working.

**Comment by akshayk10128** [comment] 2018-05-02 10:13
Hi,  I am still not able to resolve this with django rest framework .This is my django.conf 

WSGIScriptAlias / /venv/core/core/wsgi.py
WSGIPythonHome /venv
WSGIPythonPath /venv/core/core

<Directory /venv/core/core>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>

WSGIDaemonProcess core python-path=/venv/core/core/ python-home=/venv
WSGIProcessGroup core

**Comment by GrahamDumpleton** [comment] 2018-05-02 10:25
@akshayk10128 If you are not the same person who created this issue, please create a new issue.

**Comment by akshayk10128** [comment] 2018-05-02 10:34
Done , https://github.com/GrahamDumpleton/mod_wsgi/issues/308

Thanks

**Comment by GrahamDumpleton** [comment] 2018-06-29 01:10
Closing. No further followup from original poster, Assuming resolved.

**Closed by GrahamDumpleton** 2018-06-29 01:10 UTC
