### ISSUE TITLE
WSGIPythonPath additional directories error

### ISSUE THREAD

**Issue by wang19930902** [GrahamDumpleton/mod_wsgi#92] opened 2015-09-18 06:14 UTC
apache 2.2.15
python 3.5.0

When I use it to add some directories like this:
WSGIPythonPath   /var/www/wifi:/var/www/home

Apache error_log:
[Fri Sep 18 13:53:09 2015] [error] mod_wsgi (pid=31000): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Fri Sep 18 13:53:09 2015] [error] mod_wsgi (pid=31000): Call to 'site.addsitedir()' failed for '/var/www/home'.
[Fri Sep 18 13:53:09 2015] [error] mod_wsgi (pid=31000): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Fri Sep 18 13:53:09 2015] [error] mod_wsgi (pid=31000): Call to 'site.addsitedir()' failed for '/var/www/home'.
etc.

**Comment by GrahamDumpleton** [comment] 2015-09-18 12:22
Does the directory ``/var/www/home`` actually exist? Is it readable/searchable to the user that Apache runs as?

**Comment by wang19930902** [comment] 2015-09-19 05:37
the wsgipytonpath can only work without ":".
When I use ":" to split the paths, It show error.


I do a test like this:
```
 mkdir /var/www/wifi
chomd 777 /var/www/wifi
```
```
vim /var/www/wifi/wsgi.py
```
```
from flask import Flask
app = Flask(__name__)

import sys

@app.route('/')
def hello_world():
    return '<br>'.join(sys.path)

application = app
if __name__ == '__main__':
    app.run()
```


```
vim /etc/httpd/conf.d/my.conf
```
```
WSGIPythonHome /var/www/venv/
WSGIPythonPath  /var/www/wifi:/var/www/wifi/:/var/www/wifi
WSGIScriptAlias / /var/www/wifi/wsgi.py
<Directory /var/www/wifi>
<Files wsgi.py>
 Allow from all
 Order deny,allow
</Files>
</Directory>
```

```
service httpd restart
```


webshow:
```
/var/www/venv/lib/python35.zip
/var/www/venv/lib/python3.5
/var/www/venv/lib/python3.5/plat-linux
/var/www/venv/lib/python3.5/lib-dynload
/usr/lib64/python3.5
/usr/lib/python3.5
/usr/lib/python3.5/plat-linux
/var/www/venv/lib/python3.5/site-packages
```

```
cat /etc/httpd/logs/error_log
```
```
[Sat Sep 19 13:01:59 2015] [notice] Apache/2.2.15 (Unix) DAV/2 mod_wsgi/4.4.13 Python/3.5.0 configured -- resuming normal operations
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1388): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1388): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1391): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1391): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1386): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1386): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1387): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1387): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1389): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1389): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1384): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1385): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1384): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1385): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1390): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:00 2015] [error] mod_wsgi (pid=1390): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:09 2015] [error] mod_wsgi (pid=1391): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:09 2015] [error] mod_wsgi (pid=1391): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:09 2015] [error] mod_wsgi (pid=1386): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:09 2015] [error] mod_wsgi (pid=1386): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
[Sat Sep 19 13:02:25 2015] [error] mod_wsgi (pid=1392): Call to 'site.addsitedir()' failed for '(null)', stopping.
[Sat Sep 19 13:02:25 2015] [error] mod_wsgi (pid=1392): Call to 'site.addsitedir()' failed for '/var/www/wifi/:/var/www/wifi'.
```

**Comment by GrahamDumpleton** [comment] 2015-09-19 12:26
Can you try the same thing with an older Puthon version? Preferably Python 2.X to start with.

That will tell me whether is a Python 3.X or even specifically a 3.5 issue.

I am on holiday traveling at the moment so it is really hard for me to do tests myself, so any further checks you can do for me would be much appreciated.

In the mean time the workaround is to limit it to one directory in WSGIPythonPath and and use site.addsitedir() explicitly in WSGI script file to set any others.

**Comment by wang19930902** [comment] 2015-09-21 02:47
I try it in python2.7.10 . 
It work ok.
At last thank for your help!

**Comment by GrahamDumpleton** [comment] 2015-10-03 11:39
The problem is actually caused by the logging code doing the wrong thing for Python 3. Disable the logging code and it works. So need to fix up the logging code.

**Comment by GrahamDumpleton** [comment] 2015-10-03 20:28
Fixed on develop branch if want to test.

**Comment by GrahamDumpleton** [comment] 2015-10-04 11:05
Fix released with 4.4.15. Report if still issues.

**Closed by GrahamDumpleton** 2015-10-04 11:05 UTC

**Comment by spoage** [comment] 2016-05-28 08:23
@GrahamDumpleton What logging code are you referring to disabling?

I'm here via bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811077 in the debian libapache2-mod-wsgi-py3 package, and I don't have any logging code of my own to disable, unless you mean the logging configuration in my vhost file.

Can you clarify or perhaps provide an alternative work-around? I'd prefer not to override the package from the maintainer to fix this.

Thanks

**Comment by GrahamDumpleton** [comment] 2016-05-28 14:06
The reference to debugging logging code was related to me commenting out logging code in mod_wsgi itself to verify where the issue was coming from, not disabling logging of your own.

Do be aware that any mod_wsgi packages shipped by Debian and Ubuntu are unsupported by Debian or Ubuntu and neither do I support them as they ship out of date ancient versions which are many releases behind. It is basically a myth that in a LTS version of those Linux distributions that they provide support. They don't, they only do that for certain core packages and not the majority of stuff you might install. If you always use only system provided packages in the belief that they are supported, then the reality is that they aren't.

As to a workaround, it depends on what paths you are trying to add. If you had something like:

```
WSGIDaemonProcess [...] python-path=/home/srittau/.virtualenvs/foo/lib/python3.5/site-packages:/home/srittau/foo/bar/pylibs
```

where one path is that related to a virtual environment, it isn't the preferred way anyway. For a virtual environment you should use ``python-home`` option to specify the root of the virtual environment and not use ``python-path`` to specify the ``site-packages`` directory. Thus should use:

```
WSGIDaemonProcess [...] python-home=/home/srittau/.virtualenvs/foo python-path=/home/srittau/foo/bar/pylibs
```

Thus if the reason for two paths was because of one being the virtual environment, change it to the preferred setup and you should be good. If you are adding multiple directories for other reasons, this will not help and the only other option is to add the paths as part of the WSGI script file.

**Comment by spoage** [comment] 2016-05-28 21:23
I don't exclusively constrain myself to package maintainer version - I just try to use it when at all possible, which it appears to be thanks to your feedback.

I didn't know about the python-home option, and that is precisely my use case. That should get me back on track without having to deal with juggling the packages around.

Thanks very much!

**Comment by davidrdz93** [comment] 2017-08-17 18:27
This instructions save me a lot of time of issues! thank you so much...
