### ISSUE TITLE
mod_wsgi causing segfaults

### ISSUE THREAD

**Issue by joshcoughlan** [GrahamDumpleton/mod_wsgi#78] opened 2015-05-14 16:47 UTC
I upgraded our mod_wsgi to 4.4.11 and now apache is segfaulting and dying fairly often. I've managed to get coredumps and have done a gdb backtrace:

backtrace from httpd top-level process:
(gdb) bt full
#0  0x0000000000009e4e in ?? ()
No symbol table info available.
#1  0x00007f1fa65dac33 in wsgi_manage_process (reason=<value optimized out>, data=0x7f1fabb964f8, status=11) at src/server/mod_wsgi.c:7488
        mpm_state = <value optimized out>
        stopping = 1
        daemon = 0x7f1fabb964f8
#2  0x00007f1fa9014d21 in apr_proc_other_child_alert (proc=<value optimized out>, reason=<value optimized out>, status=<value optimized out>) at misc/unix/otherchild.c:115
        ocr = <value optimized out>
        nocr = <value optimized out>
#3  0x00007f1faa54e713 in ap_mpm_run (_pconf=<value optimized out>, plog=<value optimized out>, s=<value optimized out>) at /usr/src/debug/httpd-2.2.15/server/mpm/prefork/prefork.c:1068
        status = 11
        pid = {pid = 18770, in = 0x2f990d7b773477ff, out = 0x7f1fabb89338, err = 0x7f1fababb138}
        child_slot = -1
        exitwhy = 6
        processed_status = 0
        index = <value optimized out>
        remaining_children_to_start = 0
        rv = <value optimized out>
#4  0x00007f1faa5259b0 in main (argc=1, argv=0x7fff80bb4bd8) at /usr/src/debug/httpd-2.2.15/server/main.c:763
        c = 0 '\000'
        configtestonly = <value optimized out>
        confname = 0x7f1faa55035e "conf/httpd.conf"
        def_server_root = 0x7f1faa550353 "/etc/httpd"
        temp_error_log = 0x0
        error = <value optimized out>
        process = 0x7f1fabac2860
        server_conf = 0x7f1fabac2860
        pglobal = 0x7f1fabab9128
        pconf = 0x7f1fababb138
        plog = 0x7f1fabaed2c8
        ptemp = 0x7f1fababf158
        pcommands = 0x7f1fababd148
        opt = 0x7f1fababd240
        rv = <value optimized out>
        mod = <value optimized out>
        optarg = 0x7f1fabab5250 ""
        signal_server = <value optimized out>

Backtrace from pid 18770:
#0  0x0000000000009c5e in ?? ()
No symbol table info available.
#1  0x00007f1fa65d72f8 in wsgi_deadlock_thread (thd=<value optimized out>, data=<value optimized out>) at src/server/mod_wsgi.c:8459
        daemon = <value optimized out>
        gilstate = <value optimized out>
#2  0x00007f1fa8de49d1 in start_thread (arg=0x7f1f9d54a700) at pthread_create.c:301
        __res = <value optimized out>
        pd = 0x7f1f9d54a700
        now = <value optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139773760284416, -5524806647175325227, 139774001768896, 139773760285120, 0, 3, 5579057280028367317, 5579010084103903701},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <value optimized out>
        pagesize_m1 = <value optimized out>
        sp = <value optimized out>
        freesize = <value optimized out>
#3  0x00007f1fa8b318fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

I am not a programmer (systems administrator) and do not know C, but it seems to me like mod_wsgi might be trying to access a closed mutex?

**Comment by GrahamDumpleton** [comment] 2015-05-14 21:43
Duplicate of #77.

**Closed by GrahamDumpleton** 2015-05-14 21:43 UTC
Labels: duplicate
