### ISSUE TITLE
Resource Temporary Unavailable, 503 errors with increased load

### ISSUE THREAD

**Issue by jyoti-dhiman** [GrahamDumpleton/mod_wsgi#599] opened 2020-08-07 05:19 UTC
Error: 
`Resource temporarily unavailable: [client x.x.x.x:] mod_wsgi (pid=16878): Unable to connect to WSGI daemon process xx' on '/var/run/apache2/wsgi.1401.2.1.sock'.`

So, I did some changes on my running Django API(on WSGI + apache2), and it works fine with around 25% load but if the load increases, it starts throwing the above error very frequently. Also, CPU usage suddenly shoots up from 25% to nearly 100% with increased load. I went through: https://github.com/GrahamDumpleton/mod_wsgi/issues/228 and tried to do some config changes, as I guessed that maybe increased response time(150ms to 300ms) might be causing issues, my current wsgi conf looks like this:
I changed my conf from:
`processes=4 threads=30 `
to
`processes=20 threads=5 listen-backlog=200 ` (more processes, fewer threads because I read in conf that for CPU bound cases processes should be more)

503 stopped after this but I started getting 502s and following error in logs:
 continuously getting
`scoreboard is full, not at MaxRequestWorkers`
and if the load increases:
`server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting`
and CPU usage is still high.

I am not sure how to go about the solution now, how can increased response time:
- cause 502s? or 503s?
- Increase CPU usage to 90-100%?

New changes:
- create boto3 client
- push to kinesis

I have done a lot of debugging, there's nothing wrong with new changes, I am not able to release the changes due to these issues and I don't want to change to whole setup to set up a new application, can anyone help?

**Comment by GrahamDumpleton** [comment] 2020-08-07 08:31
You look to be overloading the capacity of the whole server. Is this with real traffic, or are you hammering it with a benchmarking tool and thus not true indication of traffic volume?

If this is real traffic, what is the request throughput you actually get? What are the average response times for requests, and maximum response times?

**Comment by jyoti-dhiman** [comment] 2020-08-07 10:40
Hi, so currently the system is running in production with around 150 ms of the response time of the API. Requests range around 40k per minute which is divided across two servers. 
Currently, the system runs fine.

After doing the additional changes, the response time increased to around 300ms, maximum response time would be 800-900ms, though it's very rare. I released my new changes on one machine with 40% load, so around 16000 requests per minute, and I started seeing these errors & increased CPU usage and had to revert the changes.

The other machine with 60% load + 150ms response time + old changes, was working fine.

And currently, with configuration changes, I am doing the load testing with JMeter

**Comment by GrahamDumpleton** [comment] 2020-08-07 10:48
So to confirm, you made "Python code changes in your application" and saw the change? You only tried the Apache config changes after you had issues with your application code changes.

**Comment by jyoti-dhiman** [comment] 2020-08-07 11:30
Yes!! It works fine with less load, like 7000requests per minute. In that case CPU usage is low and no 502/503 errors. Can increased queue time might be causing increased CPU usage/queue filling up/503s? I have gone through docs and researched a bit but couldn't find a solution.

Then I tried, old code + added sleep to increase response time and I started seeing 502s, so my guess is the increased response time is giving my code trouble and I really can't go lower than 300ms

**Comment by GrahamDumpleton** [comment] 2020-08-07 11:40
Long term solution would be to use an APM service to work out where your bottlenecks are and improve the perform of your application code or database queries.

Short term, if you have sufficient memory on the system, which it seems you do since you increased number of processes, is to adjust processes/threads so have overall higher number of threads across all daemon processes.

As long as memory usage of host not an issue, try with ``processes=20 threads=10``.

Watch how much CPU is used though because if that still gets too high then your code changes are just causing too much load.

Also, if you don't have any long running requests, set ``request-timeout=30`` on ``WSGIDaemonProcess``. This will act as fail safe in case the problem is that you have requests which are blocking, or getting stuck in a loop thus reducing capacity over time as the number of these grow. There is an odd calculation since you are using multithreaded, but once consumed request time across all request handler threads for active requests hits 30 second, the daemon process will be restarted. This will interrupt running requests, but better that things recover than start to hang the whole server. When processes restarted, it will also log Python stack traces of where requests stuck, which can help with debugging.

**Comment by GrahamDumpleton** [comment] 2021-08-02 01:45
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.

**Closed by GrahamDumpleton** 2021-08-02 01:45 UTC
