### ISSUE TITLE
Reload issue after an exception

### ISSUE THREAD

**Issue by jderrien** [GrahamDumpleton/mod_wsgi#198] opened 2017-04-19 14:37 UTC
Hello,

It seems that the application processes can be stuck and cannot get reloaded via the `touch` method when some kind of exceptions occurs.

When it happens, the only way to restart the app is to reload Apache. It's something which can be unexpected and annoying in production and even more in development.

I've tested and reproduced the problem with both 3.4 (Ubuntu 14.04) and 4.3.0 (Ubuntu 16.04), using daemon mode.

It seems this is the same issue as described [here](http://git.net/ml/modwsgi/2009-10/msg00160.html).

Do you know what could be wrong? Is it a known issue or something that I'm doing wrongly?

If you want to dig into this issue and cannot reproduce it, I could provide an example.

Thank you.

**Comment by GrahamDumpleton** [comment] 2017-04-20 14:08
Are you using embedded mode or daemon mode? This can happen with embedded mode. You should preferably not use embedded mode and should always use daemon mode. When touching a WSGI file in daemon mode the whole process is always reloaded but tat relies on the WSGI file having already been loaded successfully. To combat problem where a WSGI file fails to load, but where code it loads leaves state in memory, as can occur with Django, then you need to use the ``startup-timeout`` option of the ``WSGIDaemonProcess`` directive to specify a time period, after which a forced process restart will occur if the WSGI file still can't be loaded even after subsequent attempts.

See:

* http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html

**Comment by jderrien** [comment] 2017-04-21 12:17
I'm using daemon mode. I've compiled the latest version of mod_wsgi to be able to use the `startup-timeout` option, but I still have the issue.

Next step for me will be to provide a concrete example of the issue. I'll try to do it in the next few days.

**Comment by GrahamDumpleton** [comment] 2017-04-21 12:42
Sorry, didn't read your description properly. Only have limited Internet time to respond to issues at moment as am travelling.

What I missed was you saying your WSGI application was getting stuck. This implies your WSGI application had been running already and wasn't a issue with initial loading of the WSGI application as I interpreted it.

A WSGI application getting stuck is usually caused by a number of reasons. The first is application code itself deadlocking, causing all request threads to hang. This will result in touch reloading faiing as it is only checked when a new request is accepted and since all request threads are stuck, that never happens.

That you have an exception occurring could well mean that the application code is not intercepting the exception and re-raising it, after having released any thread locks. That it doesn't release locks will cause all subsequent calls into the code guarded by that lock to block, thus the deadlock.

Another possibility is that the way you are configuring mod_wsgi, you aren't using daemon mode and aren't forcing the WSGI application to run in the main interpreter. If the latter isn't done, then you can have problems with certain third party Python packages which have C extensions, as they aren't implemented correctly to work in a sub interpreter. The ``numpy`` package and anything that relies on it is a prime example of packages that can be affected by this.

So, are you forcing use of the main interpreter by including:

```
WSGIApplicationGroup %{GLOBAL}
```

The latter problem can only be worked around by ensuring the main interpreter context is used.

The first can only be addressed by fixing the application code which isn't checking for exceptions properly and releasing locks.

Daemon mode has various safeguards for these sorts of problems to recover an application, but the only one on by default is ``deadlock-timeout``, which defaults to 60 seconds. This one detects incorrect use of the Python GIL causing a deadlock.

Other sorts of problems as I describe above, can only be dealt with by supplying a request timeout. For a manually configured mod_wsgi (not mod_wsgi-express), there is not set request timeout value by default and you would need to supply one. What you supply is partly going to be determined what you application does. Presuming your response times are fast, consider setting on ``WSGIDaemonProcess`` directive the ``request-timeout`` option with value 30 or 60.

Anyway can you please supply the actual mod_wsgi configuration you are using.

**Comment by jderrien** [comment] 2017-04-24 09:43
Graham, sorry for being misleading with the 'stuck' verb, this was not clear. In fact, this is the code reload mechanism which seems to be stuck somewhere, but the app itself is still working (with the older version of the code).

It's pretty similar to the mailing list message I've linked in my first message.

I've setup a small project [here](https://github.com/jderrien/flask-reload-issue) (it uses Vagrant and Ansible). The Apache virtual host is [here](https://github.com/jderrien/flask-reload-issue/blob/master/ansible/templates/vhost_flask-reload-issue.conf.j2).

Here are the details about the second test I've described in the README file:

Initially, the application works as expected:
```
$ curl http://localhost:8080/debug
<pre>
Application is started
- pid=6301
- debug=False
- mod_wsgi.process_group='flask-reload-issue'
</pre>
```

Apache's `error.log` shows this (as expected):
```
[Mon Apr 24 09:27:08.232693 2017] [:info] [pid 6301:tid 140343668315904] mod_wsgi (pid=6301): Create interpreter 'localhost:8080|'.
[Mon Apr 24 09:27:08.255397 2017] [:info] [pid 6301:tid 140343668315904] [remote 10.0.2.2:49492] mod_wsgi (pid=6301, process='flask-reload-issue', application='localhost:8080|'): Loading WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi'.
```

Then, the application breaks:
```
$ sed -i.bck -e 's/^    #RaiseSyntaxError/    RaiseSyntaxError/' flask_reload_issue/helpers/logger.py
$ touch flask_reload_issue.wsgi

$ curl http://localhost:8080/debug
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 8080</address>
</body></html>
```

Apache's `error.log` shows this (as expected):
```
[Mon Apr 24 09:30:06.284468 2017] [:info] [pid 6301:tid 140343668315904] [remote 10.0.2.2:44628] mod_wsgi (pid=6301): Force restart of process 'flask-reload-issue'.
[Mon Apr 24 09:30:06.284701 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Shutdown requested 'flask-reload-issue'.
[Mon Apr 24 09:30:06.285139 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Stopping process 'flask-reload-issue'.
[Mon Apr 24 09:30:06.285259 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Destroying interpreters.
[Mon Apr 24 09:30:06.285392 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Destroy interpreter 'localhost:8080|'.
[Mon Apr 24 09:30:06.288951 2017] [:info] [pid 6302:tid 140343559321344] [client 10.0.2.2:52189] mod_wsgi (pid=6302): Connect after WSGI daemon process restart, attempt #1.
[Mon Apr 24 09:30:06.290032 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Cleanup interpreter ''.
[Mon Apr 24 09:30:06.324948 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Terminating Python.
[Mon Apr 24 09:30:06.337980 2017] [:info] [pid 6301:tid 140343774087040] mod_wsgi (pid=6301): Python has shutdown.
[Mon Apr 24 09:30:07.004551 2017] [:info] [pid 6475:tid 140343774087040] mod_wsgi (pid=6475): Attach interpreter ''.
[Mon Apr 24 09:30:07.066196 2017] [:info] [pid 6475:tid 140343668315904] mod_wsgi (pid=6475): Create interpreter 'localhost:8080|'.
[Mon Apr 24 09:30:07.086331 2017] [:info] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492] mod_wsgi (pid=6475, process='flask-reload-issue', application='localhost:8080|'): Loading WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi'.
[Mon Apr 24 09:30:08.173873 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492] mod_wsgi (pid=6475): Target WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi' cannot be loaded as Python module.
[Mon Apr 24 09:30:08.174094 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492] mod_wsgi (pid=6475): Exception occurred processing WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi'.
[Mon Apr 24 09:30:08.174278 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492] Traceback (most recent call last):
[Mon Apr 24 09:30:08.174422 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492]   File "/opt/flask-reload-issue/flask_reload_issue.wsgi", line 4, in <module>
[Mon Apr 24 09:30:08.175085 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492]     from application import app as application
[Mon Apr 24 09:30:08.175221 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492]   File "/opt/flask-reload-issue/flask_reload_issue/application.py", line 8, in <module>
[Mon Apr 24 09:30:08.176465 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492]     logger.configure(app)
[Mon Apr 24 09:30:08.176627 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492]   File "/opt/flask-reload-issue/flask_reload_issue/helpers/logger.py", line 6, in configure
[Mon Apr 24 09:30:08.177575 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492]     RaiseSyntaxError
[Mon Apr 24 09:30:08.177704 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:49492] NameError: global name 'RaiseSyntaxError' is not defined
```

Fix the application code, so it should work again:
```
$ mv flask_reload_issue/helpers/logger.py.bck flask_reload_issue/helpers/logger.py
$ touch flask_reload_issue.wsgi
```

But we still get a 500 error.

The Apache's `error.log` shows that the application hasn't been restarted (the PID is still the same, even if in the stack trace we see the commented line):
```
[Mon Apr 24 09:31:27.950099 2017] [:info] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628] mod_wsgi (pid=6475, process='flask-reload-issue', application='localhost:8080|'): Loading WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi'.
[Mon Apr 24 09:31:27.956133 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628] mod_wsgi (pid=6475): Target WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi' cannot be loaded as Python module.
[Mon Apr 24 09:31:27.956311 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628] mod_wsgi (pid=6475): Exception occurred processing WSGI script '/opt/flask-reload-issue/flask_reload_issue.wsgi'.
[Mon Apr 24 09:31:27.956490 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628] Traceback (most recent call last):
[Mon Apr 24 09:31:27.956690 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628]   File "/opt/flask-reload-issue/flask_reload_issue.wsgi", line 4, in <module>
[Mon Apr 24 09:31:27.957771 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628]     from application import app as application
[Mon Apr 24 09:31:27.957903 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628]   File "/opt/flask-reload-issue/flask_reload_issue/application.py", line 8, in <module>
[Mon Apr 24 09:31:27.958215 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628]     logger.configure(app)
[Mon Apr 24 09:31:27.958348 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628]   File "/opt/flask-reload-issue/flask_reload_issue/helpers/logger.py", line 6, in configure
[Mon Apr 24 09:31:27.959718 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628]     #RaiseSyntaxError
[Mon Apr 24 09:31:27.959877 2017] [:error] [pid 6475:tid 140343668315904] [remote 10.0.2.2:44628] NameError: global name 'RaiseSyntaxError' is not defined
```

**Comment by GrahamDumpleton** [comment] 2017-04-28 11:58
Sorry for the slow reply, am back home after my holiday now.

This is the exact sort of problem which the ``startup-timeout`` option of ``WSGIDaemonProcess`` option is designed to combat.

The reason touching the WSGI script file doesn't work is because the WSGI script file hadn't actually been successfully loaded within the process still and so it isn't strictly a reload, but is still seen as a first attempt to load it as their is no loaded module for the WSGI script file to compare date/time stamps against. 

So what happened was that when an attempt was made to first load it in the process it failed, but the failure was not in the WSGI script file, but when calling a module imported by it. When a failure occurs like this, the module corresponding to the WSGI script file is deleted, but the module with the bad code will persist in memory. The startup timeout is deals with this by detecting that there hasn't been a successful load of a WSGI script file after some time, and so this is interpreted as possibility successive load failures. When the startup timeout is reached, the process will be restarted to throw everything out of memory.

**Comment by jderrien** [comment] 2017-04-28 15:43
Don't be sorry. I hope you had a good holiday!

I understand but I still reproduce this issue with mod_wsgi 4.5.15 and adding `startup-timeout=5`. Maybe I'm wrong somewhere, but I can't see where.

On the Vagrant box I installed mod_wsgi with:
```sudo apt-get install apache2-dev python-dev
curl -L -O https://github.com/GrahamDumpleton/mod_wsgi/archive/4.5.15.tar.gz
tar xzf 4.5.15.tar.gz
cd mod_wsgi-4.5.15/
./configure
make
make install```

Then I updated this line in the config:
```WSGIDaemonProcess flask-reload-issue processes=1 threads=1 python-home=/opt/flask-reload-issue/venv startup-timeout=5```

I've also checked the version of mod_wsgi with `mod_wsgi.version` and it's the right one.

Would you have any idea? Thank you.

**Comment by GrahamDumpleton** [comment] 2017-05-08 01:55
If you can try fix in develop branch to verify, that would be good.

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

I will probably release new version with change soon either way.

Note you still require ``startup-timeout`` to recover from that scenario. Issue was I managed to break the feature with that fix for something else in 2.5.10.

**Comment by jderrien** [comment] 2017-05-08 15:11
Hmm, I still reproduce the error with the develop version (4.5.16) and still using `startup-timeout=5`.

```
WSGIDaemonProcess flask-reload-issue processes=1 threads=1 python-home=/opt/flask-reload-issue/venv startup-timeout=5
```

Do you know what could be wrong?

**Comment by GrahamDumpleton** [comment] 2017-05-10 04:44
My steps using ``mod_wsgi-express``.

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

Run ``mod_wsgi-express``.

```
$ mod_wsgi-express start-server --log-to-terminal --log-level info --python-path flask_reload_issue flask_reload_issue.wsgi
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:502
Server Conf        : /tmp/mod_wsgi-localhost:8000:502/httpd.conf
Error Log File     : /dev/stderr (info)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_AU.UTF-8
[Wed May 10 14:23:18.793863 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947): Starting process 'localhost:8000' with threads=5.
[Wed May 10 14:23:18.793881 2017] [mpm_prefork:notice] [pid 85945] AH00163: Apache/2.4.18 (Unix) mod_wsgi/4.5.16 Python/2.7 configured -- resuming normal operations
[Wed May 10 14:23:18.794121 2017] [mpm_prefork:info] [pid 85945] AH00164: Server built: Feb 20 2016 20:03:19
[Wed May 10 14:23:18.794135 2017] [core:notice] [pid 85945] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /tmp/mod_wsgi-localhost:8000:502/httpd.conf -D MOD_WSGI_WITH_PYTHON_PATH -D FOREGROUND'
[Wed May 10 14:23:18.794505 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947): Python home /Users/graham/Python/flask.
[Wed May 10 14:23:18.794528 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947): Initializing Python.
[Wed May 10 14:23:18.804300 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947): Attach interpreter ''.
[Wed May 10 14:23:18.805404 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947): Adding 'flask_reload_issue' to path.
[Wed May 10 14:23:18.806781 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947): Imported 'mod_wsgi'.
[Wed May 10 14:23:18.806840 2017] [wsgi:info] [pid 85947] mod_wsgi (pid=85947, process='localhost:8000', application=''): Loading WSGI script '/tmp/mod_wsgi-localhost:8000:502/handler.wsgi'.
```

Make request. Will succeed.

```
$ curl http://localhost:8000/debug
<pre>
Application is started
- pid=85947
- debug=False
- mod_wsgi.process_group='localhost:8000'
</pre>
```

Break the file and force reload by touching WSGI script file.

```
$ sed -i.bck -e 's/^    #RaiseSyntaxError/    RaiseSyntaxError/' flask_reload_issue/helpers/logger.py
$ touch flask_reload_issue.wsgi
```

Make request. Will fail.

Note that because WSGI script file was touched, a process reload was done. Because of the bad code, the WSGI script file could not actually be loaded in the new process.

```
$ curl http://localhost:8000/debug
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

Put back good code and force reload again.

```
$ mv flask_reload_issue/helpers/logger.py.bck flask_reload_issue/helpers/logger.py
$ touch flask_reload_issue.wsgi
```

Make request. But it needs to be done quick enough that is done before the startup timeout (presuming it is set) expires.

This will still fail at this point because the WSGI script file wasn't already loaded at that point, so touching the WSGI script file makes no difference as has to load it from scratch. In other words, no way to know a process reload should be done.

The problem is the broken logger code is still loaded in the process and so it fails.

```
$ curl http://localhost:8000/debug
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

So that it failed here is actually expected.

If you wait however for the startup timeout to now expire, because the WSGI script couldn't be loaded successfully, even with subsequent requests, the process will be force restarted.

```
[Wed May 10 14:26:36.596946 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Application startup timer expired, stopping process 'localhost:8000'.
[Wed May 10 14:26:36.597194 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Shutdown requested 'localhost:8000'.
[Wed May 10 14:26:36.597264 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Stopping process 'localhost:8000'.
[Wed May 10 14:26:36.597273 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Destroying interpreters.
[Wed May 10 14:26:36.597278 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Cleanup interpreter ''.
[Wed May 10 14:26:36.597436 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Terminating Python.
[Wed May 10 14:26:36.608846 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Python has shutdown.
[Wed May 10 14:26:36.608867 2017] [wsgi:info] [pid 85961] mod_wsgi (pid=85961): Exiting process 'localhost:8000'.
[Wed May 10 14:26:37.432597 2017] [wsgi:info] [pid 85945] mod_wsgi (pid=85961): Process 'localhost:8000' has died, deregister and restart it.
[Wed May 10 14:26:37.432635 2017] [wsgi:info] [pid 85945] mod_wsgi (pid=85961): Process 'localhost:8000' terminated normally, exit code 0
[Wed May 10 14:26:37.432638 2017] [wsgi:info] [pid 85945] mod_wsgi (pid=85961): Process 'localhost:8000' has been deregistered and will no longer be monitored.
[Wed May 10 14:26:37.433326 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967): Starting process 'localhost:8000' with threads=5.
[Wed May 10 14:26:37.433829 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967): Python home /Users/graham/Python/flask.
[Wed May 10 14:26:37.433855 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967): Initializing Python.
[Wed May 10 14:26:37.449811 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967): Attach interpreter ''.
[Wed May 10 14:26:37.451159 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967): Adding 'flask_reload_issue' to path.
[Wed May 10 14:26:37.453363 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967): Imported 'mod_wsgi'.
[Wed May 10 14:26:37.453466 2017] [wsgi:info] [pid 85967] mod_wsgi (pid=85967, process='localhost:8000', application=''): Loading WSGI script '/tmp/mod_wsgi-localhost:8000:502/handler.wsgi'.
```

Make a request now and things are okay.

```
$ curl http://localhost:8000/debug
<pre>
Application is started
- pid=85967
- debug=False
- mod_wsgi.process_group='localhost:8000'
</pre>
```

So it is a bit odd how requests still fail until startup timeout occurs, but it is tricky to do otherwise.

What would be necessary is to keep a record somehow of all failed WSGI script loads in a table, along with time stamp of the file when loaded failed. Next time the WSGI script file is loaded, if time stamp has changed since last attempt at loading it, force a process restart first.

I have considered something like this table in the past, but for various reasons I can't really remember ruled it out. The easiest I could come up with was the process wide startup timeout on being able to load a WSGI script file into a new process. This does come with restrictions though in that only really works well if there is the one WSGI application per daemon process group.

I would have to go back and think again about tracking the separate table of timestamps for failed WSGI script file loads so have something to compare timestamp against when re-attempting reloaded. The table approach isn't going to help in subset of cases, and can't handle other cases that startup timeout can, such an initial failed database connection during Django initialisation. In that case it isn't a code problem, but problem with talking to backend service that screws up Django initialisation and causes all subsequent requests with same WSGI script file to fail.

Are you testing with the startup timeout and do you not see messages in logs to say process was reloaded after the startup timeout period, after which it then worked.

**Comment by aggieNick02** [comment] 2017-09-19 19:55
One option to be considered is preventing exceptions from being thrown out of the wsgi file.

I was encountering the same problem, but with django/apache due to syntax errors in my models file. I noticed the docs encourage the use of startup-timeout to deal with this scenario, but it is a fairly new addition and not in a version I can easily move to. Plus I'm not crazy about picking an arbitrary timeout for startup-timeout.

I worked around this by putting a try/except in my wsgi file so that the WSGI script always loads even when things go wrong. To keep the stack trace in the apache logs I added logging.exception('Exception starting django') in the except. With this, my processes always reload after touching the wsgi file, and I don't notice any ill effects (yet).

**Comment by GrahamDumpleton** [comment] 2017-09-19 20:01
The ``startup-timeout`` option was added a year ago so it isn't really new. If you are using operating system packages for mod_wsgi you really should consider installing mod_wsgi yourself. The operating system packages for distros such as Debian and Ubuntu are not supported and don't get fixed.

**Comment by aggieNick02** [comment] 2017-09-19 20:07
Thanks for the feedback; I'm new to linux/apache so it's appreciated. Do you see any drawbacks to putting the exception handling in the wsgi file?

**Comment by GrahamDumpleton** [comment] 2017-09-19 20:12
Depends on what WSGI framework you are using and also the nature of the exception which is occurring, whether it is transient, and whether it leaves the process in an intermediate state that cannot be recovered. Also depends on what you are doing in the event of an exception. So hard to say without more information.

BTW, if you are worried about complexity of installing mod_wsgi, make sure you look at the ``pip install mod_wsgi`` method of installing it as described at:

* https://pypi.python.org/pypi/mod_wsgi

This is easier than traditional method of download source code and doing configure/make/make install.

**Comment by HoangJerry** [comment] 2018-01-03 07:00
[Wed Jan 03 14:55:34.406034 2018] [wsgi:error] [pid 10056:tid 140103647160064] [remote 171.251.17.2:40036] mod_wsgi (pid=10056): Target WSGI script '/opt/django-react-davidho/ez_claims/ez_claims/wsgi.py' cannot be loaded as Python module.
[Wed Jan 03 14:55:34.406066 2018] [wsgi:error] [pid 10056:tid 140103647160064] [remote 171.251.17.2:40036] mod_wsgi (pid=10056): Exception occurred processing WSGI script '/opt/django-react-davidho/ez_claims/ez_claims/wsgi.py'.
[Wed Jan 03 14:55:34.406099 2018] [wsgi:error] [pid 10056:tid 140103647160064] [remote 171.251.17.2:40036] Traceback (most recent call last):
[Wed Jan 03 14:55:34.406115 2018] [wsgi:error] [pid 10056:tid 140103647160064] [remote 171.251.17.2:40036]   File "/opt/django-react-davidho/ez_claims/ez_claims/wsgi.py", line 16, in <module>
[Wed Jan 03 14:55:34.406160 2018] [wsgi:error] [pid 10056:tid 140103647160064] [remote 171.251.17.2:40036]     application = get_wsgi_application()

**Comment by GrahamDumpleton** [comment] 2018-01-03 07:04
@HoangJerry Create a separate issue, please don't add your own problem as comment on existing issue, especially when looks different. When you create the separate issue, supply the full stack trace and details of the exception. You have left it off. If you are seeing issue about Django not being re-entrant, ensure you are getting the first error after the server start, not the last.

**Closed** 2018-01-09 04:19 UTC
