### ISSUE TITLE
Daemon-mode Apache process not reloading when top-level script touched

### ISSUE THREAD

**Issue by ccazabon** [GrahamDumpleton/mod_wsgi#151] opened 2016-08-24 18:38 UTC
I've got an application that for many years has relied on reloading the top-level script when it changes (specifically, when `touch`ed) under Apache, using a daemon-mode process and process group.

Today, for some reason, I noticed that this reload mechanism did not seem to be working.  After an update of the application code (which involves installing a newer egg, which updates the easy-install.pth file to point to the newer egg's directory), the top level script (which I call a .wsgi file) gets `touch`ed to update it, and cause the code to be reloaded without having to issue an explicit `restart` or `graceful` to Apache.

But today, after updating the code in this way, it was clearly still running the old code.  I was hitting bugs fixed in the newer version, and the tracebacks getting spit to the Apache logs pointed into the old version's egg directory.

I verified that touching the .wsgi script file didn't fix the issue, but that an `apache2ctl graceful` did.

I'm current using mod_wsgi 4.4.21 (though none of the newer versions' release notes mention any issue like this) with Apache 2.4.7 (Ubuntu package).

The Apache/mod_wsgi config for the application is pretty basic:

>    # virtualenv with Pylons installed:
>    WSGIDaemonProcess example \
>        python-path=/var/www/example.com/lib/python2.7/site-packages \
>        processes=3 threads=8 maximum-requests=1000 \
>        display-name=example.com
> 
>    WSGIProcessGroup example
>    WSGIScriptAlias / /var/www/example.com/app/example-script.wsgi

Is there any reason that touching the top-level script wouldn't restart the affected processes when new requests come in?

Thanks,

Charles

**Comment by GrahamDumpleton** [comment] 2016-08-24 22:48
Do you run with:

```
LogLevel info
```

That will result in mod_wsgi logging stuff about reloading.

Would be curious if you see it again whether when you do touch it that anything is logged about it.

I do sort of recollect one instance myself where I saw touching the WSGI script didn't do anything. I can't remember the circumstances though and what the cause was. I will have to think about what happened the time I saw it.

**Comment by ccazabon** [comment] 2016-08-25 16:50
Unfortunately, no, the system in question was at the default `warn` level.  And `touch`ing the .wsgi file today appears to have done the right thing.

I'll enable info-level logging and see if I can reproduce it.  As I've never noticed this problem before, I have no idea how often it happens.  It normally Just Works.

**Comment by GrahamDumpleton** [comment] 2016-11-13 06:12
Closing as believe no action required.

**Closed by GrahamDumpleton** 2016-11-13 06:12 UTC
