### ISSUE TITLE
Thousands of "(wsgi:sign1.n.xia -k start" processes and memory leak

### ISSUE THREAD

**Issue by demonguy** [GrahamDumpleton/mod_wsgi#109] opened 2015-12-24 08:04 UTC
I happened to find that my apache2 server memory usage will grow as time goes by, and after some time, i can see thousand of wsgi processes.

after ps -ef, i can see 2114 wsgi processes like this

.....
`www-data  8499  0.0  0.0 16787804 2384 ?       S    Dec03   0:00 (wsgi:sign1.n.xia -k start`
.....

In what circumstance wsgi will fork processes like this?

**Comment by GrahamDumpleton** [comment] 2015-12-24 08:09
It doesn't have to be mod_wsgi, it can be something in the specific Python web application you are running. This is usually the cause of such problems and can occur when code forks a process in some way and doesn't wait on the exited process to retrieve its exit status. The result is that it hangs around as a zombie process.

What you need to do to determine what sort of process it is, is to look at the following.

* The process state using 'ps' to determine if it is marked as a zombie process.
* The process tree using 'pstree' or 'top' or 'htop' in tree view, to see if these are actually direct child processes of the main Apache parent process, or of a next level WSGI process.

If they are zombie processes and also a child of another WSGI process, they are most definitely caused by the web application code.

A final thing you can do is ensure that 'LogLevel' is set to 'info' in the Apache configuration. With this set, mod_wsgi will clearly log when it is starting and stopping processes or when child processes crash.

**Comment by demonguy** [comment] 2015-12-25 03:03
My application does create new processes. I just use 
`multiprocessing.Pool(processes=1)`
`Pool.apply`. And `apply` can return.
Does it cause problem?

**Comment by demonguy** [comment] 2015-12-25 08:31
Thanks for your information. I found what's wrong
Every web request my application will create a pool, and just use it for once without closing it and left the processes there.

**Closed** 2015-12-25 08:31 UTC
